// src/criteria/bakeryCriteria.ts
// Phase 3.5 ✅: bakeryCriteria for bakery/pastry establishments (Algerian law)
// W2 fix 2026-08-07: L-02 HACCP article corrected Art. 4 → Art. 5 (Décret 17-140)

import { InspectionItem } from '../types';

export const bakerySpecificCriteria: InspectionItem[] = [
  {
    id: 'BAK-01',
    axis: 'الأماكن وشروط البنية التحتية',
    category: 'هيكلية',
    criteria: 'وجود فصل واضح بين مناطق الإنتاج والتخزين والبيع والتنظيف لمنع التلوث المتبادل.',
    legalReference: 'المرسوم التنفيذي 17-140 المتعلق بشروط النظافة العامة في المؤسسات الغذائية (المادة 13 والمادة 14: تنظيم المرافق وتدفق العمليات).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-02',
    axis: 'الأماكن وشروط البنية التحتية',
    category: 'هيكلية',
    criteria: 'الأرضيات والجدران والأسقف مصنوعة من مواد غير قابلة للنفاذ وسهلة التنظيف.',
    legalReference: 'المرسوم التنفيذي 17-140 (المواد 15-17: الأرضيات والجدران والأسقف في المؤسسات الغذائية).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-03',
    axis: 'نظافة الأدوات والمعدات',
    category: 'نظافة',
    criteria: 'أدوات العجن والتشكيل والخبز مصنوعة من مواد غذائية معتمدة، وتُنظَّف وتُعقَّم بانتظام.',
    legalReference: 'القانون 09-03 المتعلق بحماية المستهلك وقمع الغش (المادة 6: المواد المتلامسة مع الغذاء).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-04',
    axis: 'تخزين المواد الخام',
    category: 'غذائية',
    criteria: 'تخزين الدقيق، السكر، والزيوت في ظروف ملائمة (جافة، مهواة، بعيداً عن الرطوبة والحرارة المباشرة).',
    legalReference: 'المرسوم التنفيذي 17-140 (المادة 23: شروط تخزين المواد الغذائية الأولية).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-05',
    axis: 'تخزين المواد الخام',
    category: 'غذائية',
    criteria: 'احترام مبدأ FIFO في استخدام المواد الخام (أول داخل أول خارج) لتجنب تجاوز تواريخ الصلاحية.',
    legalReference: 'القانون 09-03 والمرسوم 17-140 (التحقق من صلاحية المواد الغذائية).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-06',
    axis: 'تخزين المنتجات النهائية',
    category: 'غذائية',
    criteria: 'المنتجات المعبأة والمصنوعة محمية من التلوث خلال التخزين (أرفف نظيفة، تغليف مناسب).',
    legalReference: 'المرسوم التنفيذي 17-140 (شروط حفظ المنتجات الغذائية النهائية).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-07',
    axis: 'المياه والتطهير',
    category: 'بيئية',
    criteria: 'استخدام ماء صالح للشرب في جميع مراحل الإنتاج (العجن، التنظيف).',
    legalReference: 'المرسوم التنفيذي 11-125 المتعلق بجودة مياه الاستهلاك البشري.',
    severity: 'high',
    controlType: 'test',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-08',
    axis: 'المياه والتطهير',
    category: 'بيئية',
    criteria: 'التخلص من مياه الصرف الصناعي بطريقة مطابقة (صرف في الشبكة البلدية أو محطة معالجة).',
    legalReference: 'القانون 03-10 المتعلق بحماية البيئة (المادة 54: حظر تلوث المياه).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-09',
    axis: 'صحة وسلامة العمال',
    category: 'صحة مهنية',
    criteria: 'جميع العمال يرتدون ملابس عمل نظيفة ومناسبة (مريلة، غطاء رأس، حذاء مخصص).',
    legalReference: 'المرسوم التنفيذي 17-140 (المادة 21: ملابس العمل في المنشآت الغذائية).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // W2 fix 2026-08-07: L-02 Art. 4 → Art. 5 (Décret 17-140 HACCP obligation)
    id: 'BAK-10',
    axis: 'نظام HACCP',
    category: 'تنظيمية',
    criteria: 'تطبيق نظام HACCP أو إجراءات مبنية على مبادئه لتحليل المخاطر وضبط نقاط التحكم الحرجة في عملية الخبز والتصنيع.',
    legalReference: 'المادة 5 من المرسوم التنفيذي 17-140 المؤرخ في 27 مارس 2017 الذي يُلزم المنشآت الغذائية بتطبيق نظام HACCP وتوثيق إجراءاته.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-11',
    axis: 'التسمية والإعلام',
    category: 'تنظيمية',
    criteria: 'المنتجات المعبأة تحمل بطاقات إعلامية مطابقة للمواصفات (المكونات، تاريخ الإنتاج والصلاحية، الشروط).',
    legalReference: 'المرسوم التنفيذي 17-140 + القانون 09-03 (المادة 18: إعلام المستهلك).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BAK-12',
    axis: 'مكافحة الآفات',
    category: 'نظافة',
    criteria: 'وجود برنامج مكتوب لمكافحة الحشرات والقوارض، مع سجلات التدخلات المنجزة.',
    legalReference: 'المرسوم التنفيذي 17-140 (المادة 33: مكافحة الآفات في المؤسسات الغذائية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
