// src/baseFoodCriteria.ts
import { InspectionItem } from '../types';

export const baseFoodCriteria: InspectionItem[] = [
  // المحور 1 (إضافي) – الاعتماد الصحي والتراخيص الغذائية
  {
    id: 'BFD-01-01',
    axis: 'الاعتماد الصحي والتراخيص',
    category: 'تنظيمية',
    criteria: 'الاعتماد الصحي أو الترخيص الصحي عند الاقتضاء في الأنشطة الغذائية.',
    legalReference: 'المرسوم التنفيذي 17-140 المتعلق بشروط النظافة والنظافة الصحية في المؤسسات الغذائية.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 5: تجهيزات حفظ وتحضير الأغذية
  {
    id: 'BFD-05-01',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحية',
    // CE-5: replaced undated "القرار الوزاري المشترك 2020 المتعلق بـ HACCP" with the verifiable instrument
    criteria: 'توفر ثلاجات وغرف تبريد مزودة بميزان حرارة داخلي مقروء.',
    legalReference: 'المرسوم 17-140 + أدلة GHP (الممارسات الجيدة للنظافة) المعتمدة بموجب القرار الوزاري المشترك المتعلق بشروط النظافة الصحية في مناطق تحضير وتداول المواد الغذائية — ملاحظة: رقم القرار الوزاري المحدد بحاجة تحقق قبل النشر (OQ-7).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-02',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحية',
    criteria: 'حفظ الأغذية المبردة في درجة حرارة بين 0 و 5°م حسب طبيعة المنتوج.',
    legalReference: 'المرسوم 17-140 + القرارات الوزارية الخاصة بالتخزين البارد.',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: '°C',
      labelAr: 'درجة حرارة الثلاجة (أغذية مبردة)',
      min: 0,
      max: 5,
      warningMax: 7,
      step: 0.1,
    },
  },
  {
    id: 'BFD-05-03',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحية',
    criteria: 'حفظ الأغذية المجمدة في درجة حرارة -18°م أو أقل.',
    legalReference: 'القراراد الوزارية المتعلقة بالتجميد.',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: '°C',
      labelAr: 'درجة حرارة الفريزر (أغذية مجمدة)',
      min: -100,
      max: -18,
      warningMax: -15,
      step: 0.5,
      upperLimit: true,
    },
  },
  {
    id: 'BFD-05-04',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحية',
    criteria: 'فصل واضح بين المواد الأولية والمنتجات الجاهزة في التحضير والتخزين لتجنب التلوث المتبادل.',
    legalReference: 'المرسوم 17-140 + مبادئ HACCP.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-05',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحية',
    criteria: 'أسطح تحضير ملساء، غير منفذة، غير سامة، سهلة التطهير.',
    legalReference: 'المرسوم 17-140.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-06',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحية',
    criteria: 'توفر الماء الساخن للغسل في مناطق التحضير والتنظيف.',
    legalReference: 'المرسوم 17-140.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-07',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحية',
    criteria: 'تنظيف المعدات وفق تسلسل: غسل – شطف – تعقيم – تجفيف، مع توثيق عند الاقتضاء.',
    legalReference: 'المرسوم 17-140 + أدلة GHP.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 6: صحة وسلوك العمال (مع تفاصيل غذائية)
  {
    id: 'BFD-06-01',
    axis: 'صحة وسلوك العمال',
    category: 'صحية',
    criteria: 'ارتداء لباس عمل نظيف، وأغطية رأس، ووسائل وقاية شخصية حسب طبيعة المهام.',
    legalReference: 'المرسوم 17-140.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-06-02',
    axis: 'صحة وسلوك العمال',
    category: 'صحية',
    criteria: 'توفر أحواض غسل اليدين بالصابون والماء الدافئ ومناشف أحادية الاستعمال قرب مناطق العمل.',
    legalReference: 'المرسوم 17-140.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-06-03',
    axis: 'صحة وسلوك العمال',
    category: 'صحية',
    criteria: 'إخضاع العمال لفحص طبي قبل التوظيف وفحوصات طبية دورية (كل 6 أشهر في قطاع الأغذية).',
    legalReference: 'القانون 18-11 + المرسوم التنفيذي 93-120 (طب العمل والفحوص الدورية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-06-04',
    axis: 'صحة وسلوك العمال',
    category: 'صحية',
    criteria: 'منع الأكل والشرب والتدخين والبصق في أماكن تداول الأغذية والعمل الإنتاجي.',
    legalReference: 'المرسوم 17-140.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // مكافحة النواقل إضافية للغذاء
  {
    // BFD-07-01 kept: window/opening screens are food-specific, not in BGN
    id: 'BFD-07-01',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'تركيب شبكات معدنية (شباك) على النوافذ والفتحات المطلة على الخارج، سهلة النزع للتنظيف.',
    legalReference: 'المرسوم 17-140.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // S9: BFD-07-02 removed — pest monitoring map/program covered by BGN-07-02
  // المحور 8: إمكانية التتبع (S5-2 — مشترك لجميع المنشآت الغذائية)
  {
    id: 'BFD-08-01',
    axis: 'إمكانية التتبع',
    category: 'تنظيمية',
    criteria: 'وجود سجل تتبع يتضمن مصدر كل منتوج غذائي (مورد، تاريخ الاستلام، رقم الدفعة، تاريخ الصلاحية) وسجل خروج توزيع، بحيث يتسنى استرجاع أي منتوج خلال 24 ساعة.',
    legalReference: 'القانون 09-03 المتعلق بحماية المستهلك وقمع الغش (أحكام التتبع) + المرسوم التنفيذي 17-140.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 9: خطة HACCP (مشتركة للمنشآت ذات خطورة عالية) (S5-1)
  {
    id: 'BFD-09-01',
    axis: 'خطة HACCP',
    category: 'تنظيمية',
    criteria: 'وجود خطة HACCP موثقة تتضمن تحليل المخاطر وتحديد نقاط التحكم الحرجة (CCPs) وخطط المراقبة والتصحيح. منطبق بصفة إلزامية على منشآت الذبح والمجازر وغرف التبريد ومخابز العجائن، ويُوصى به لسائر المنشآت الغذائية.',
    legalReference: 'المرسوم التنفيذي 17-140 + مبادئ هيئة دولية CODEX ALIMENTARIUS بشأن HACCP — ملاحظة: رقم القرار الوزاري المحلي المحدد بحاجة تحقق قبل النشر (OQ-7).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
