// src/baseGeneralCriteria.ts
import { InspectionItem } from '../types';

export const baseGeneralCriteria: InspectionItem[] = [
  // المحور 1: هوية المنشأة والوثائق (عام)
  {
    id: 'GEN-01-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'رخصة الاستغلال سارية المفعول ومطابقة لنوع النشاط (منشأة مصنفة وفق الفئة الملائمة).',
    legalReference: 'المرسوم التنفيذي 06-198 المتعلق بالمؤسسات المصنفة (شروط وكيفيات استغلال المنشآت المصنفة).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-01-02',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'وجود سجلات للتطهير، مراقبة درجات الحرارة (عند الاقتضاء)، نتائج التحاليل، والإعذارات السابقة محفوظة ومتاحة للمراقبة.',
    legalReference: 'القانون 03-10 (حماية البيئة) + القانون 09-03 (حماية المستهلك وقمع الغش) والتشريعات التطبيقية.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 2: الموقع والتهيئة العامة (عام)
  {
    id: 'GEN-02-01',
    axis: 'الموقع والتهيئة العامة',
    category: 'بيئية',
    criteria: 'موقع المنشأة بعيد عن مصادر التلوث الظاهر (مفرغة، مياه راكدة، دخان صناعي).',
    legalReference: 'القانون 90-29 المتعلق بالتهيئة والتعمير + القانون 03-10 المتعلق بحماية البيئة.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-02-02',
    axis: 'الموقع والتهيئة العامة',
    category: 'بيئية',
    criteria: 'نشاط المنشأة لا يسبب ضررًا للساكنة المجاورة (ضجيج، روائح، انبعاثات، اهتزازات).',
    legalReference: 'القانون 03-10 (حماية البيئة) + القانون 90-29 (التهيئة والتعمير).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-02-03',
    axis: 'الموقع والتهيئة العامة',
    category: 'بيئية',
    criteria: 'نشاط المنشأة لا يسبب ضررًا للتربة الفلاحية أو المياه الجوفية.',
    legalReference: 'القانون 03-10 (حماية البيئة في إطار التنمية المستدامة).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-02-04',
    axis: 'الموقع والتهيئة العامة',
    category: 'تنظيمية',
    criteria: 'المبنى مشيَّد بمواد صلبة ومطابق لرخصة البناء وشهادة المطابقة عند الاقتضاء.',
    legalReference: 'القانون 90-29 (رخصة البناء وشهادة المطابقة) + المرسوم 06-198 (مطابقة الواقع للملف التقني).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-02-05',
    axis: 'الموقع والتهيئة العامة',
    category: 'نظافة',
    criteria: 'أرضيات وجدران قابلة للتنظيف (حسب طبيعة النشاط)، ويفضل أن تكون ملساء وغير منفذة في الأنشطة التي تتطلب ذلك.',
    legalReference: 'المعايير العامة للنظافة في المنشآت الصناعية والخدماتية.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-02-06',
    axis: 'الموقع والتهيئة العامة',
    category: 'بيئية',
    criteria: 'تهوية طبيعية أو ميكانيكية كافية حسب طبيعة النشاط.',
    legalReference: 'القانون 03-10 (جودة الهواء في أماكن العمل).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-02-07',
    axis: 'الموقع والتهيئة العامة',
    category: 'نظافة',
    criteria: 'إضاءة طبيعية أو اصطناعية كافية في أماكن العمل.',
    legalReference: 'مقتضيات الصحة والسلامة المهنية.',
    severity: 'low',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // المحور 3: المياه والصرف الصحي (عام)
  {
    id: 'GEN-03-01',
    axis: 'المياه والصرف الصحي',
    category: 'بيئية',
    criteria: 'توفر ماء صالح للشرب من شبكة عمومية أو خزان مراقَب في كل الأوقات وبضغط كافٍ.',
    legalReference: 'المرسوم التنفيذي 88-164 (مواصفات مياه الشرب).',
    severity: 'high',
    controlType: 'test',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-03-02',
    axis: 'المياه والصرف الصحي',
    category: 'بيئية',
    criteria: 'وجود شبكة صرف صحي فعالة، دون تسربات أو ركود مياه مستعملة.',
    legalReference: 'القانون 01-19 (تسيير النفايات) + القانون 03-10.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-03-03',
    axis: 'المياه والصرف الصحي',
    category: 'بيئية',
    criteria: 'صرف مياه الغسل إلى شبكة الصرف الصحي أو محطة معالجة، وعدم طرحها مباشرة في الساحة أو التربة.',
    legalReference: 'القانون 01-19 + التزامات رخصة التفريغ.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-03-04',
    axis: 'المياه والصرف الصحي',
    category: 'بيئية',
    criteria: 'تصميم قنوات الصرف غير متكسِّرة، ذات أقطار كافية، ومنحدرات ملائمة لتفادي الركود والانسداد.',
    legalReference: 'قواعد الهندسة الصحية.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-03-05',
    axis: 'المياه والصرف الصحي',
    category: 'بيئية',
    criteria: 'وجود حواجز مائية (سيفونات) في نقاط الصرف لمنع رجوع الروائح والغازات والحشرات.',
    legalReference: 'قواعد الصحة العمومية والتهيئة الصحية للمنشآت.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-03-06',
    axis: 'المياه والصرف الصحي',
    category: 'بيئية',
    criteria: 'في حالة وجود حفرة متعفنة (fosse septique): تسييرها وفق عقد مع الديوان الوطني للتطهير ONA ومعالجة المواد المستخرجة.',
    legalReference: 'القانون 01-19 + المرسوم 01-102.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 4: النظافة العامة وتسيير النفايات (عام)
  {
    id: 'GEN-04-01',
    axis: 'النظافة العامة وتسيير النفايات',
    category: 'نظافة',
    criteria: 'وضع النفايات في حاويات مغلقة أو أكياس بلاستيكية مخصصة وعدم تركها مكشوفة.',
    legalReference: 'القانون 01-19 (تسيير النفايات ومراقبتها وإزالتها).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-04-02',
    axis: 'النظافة العامة وتسيير النفايات',
    category: 'نظافة',
    criteria: 'تنظيف وتعقيم حاويات النفايات بعد التفريغ بانتظام.',
    legalReference: 'القانون 01-19.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-04-03',
    axis: 'النظافة العامة وتسيير النفايات',
    category: 'نظافة',
    criteria: 'وجود برنامج تنظيف يومي للأرضيات والجدران والتجهيزات مع وسائل ومواد تنظيف ملائمة.',
    legalReference: 'مبادئ النظافة العامة.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-04-04',
    axis: 'النظافة العامة وتسيير النفايات',
    category: 'نظافة',
    criteria: 'عدم وجود تراكم للنفايات في محيط المبنى أو في الساحة المجاورة.',
    legalReference: 'القانون 01-19 + 03-10.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // المحور 7: مكافحة النواقل (عام)
  {
    id: 'GEN-07-01',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'عدم ظهور دلائل إصابة بقوارض أو حشرات (فضلات، أثر قرض، مسارات، روائح، حشرات حية أو ميتة) داخل أو خارج المؤسسة.',
    legalReference: 'القانون 03-10 (حماية البيئة والصحة العمومية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-07-02',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'وجود برنامج دوري مكتوب لمكافحة القوارض والحشرات (تعاقد مع مؤسسة مختصة أو تدخل ذاتي موثق).',
    legalReference: 'القانون 03-10.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-07-03',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'حاويات النفايات مغلقة ومحفوظة في مكان مناسب.',
    legalReference: 'القانون 01-19.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-07-04',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'سدّ الشقوق والفراغات في الجدران وحول الأنابيب ونقاط عبور الأسلاك لمنع دخول الآفات.',
    legalReference: 'مبادئ مكافحة الآفات.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-07-05',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'استعمال مبيدات حشرية مرخّصة من طرف مؤسسات مؤهلة، واحترام فترات الغلق والتهوية.',
    legalReference: 'القانون 03-10.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 8: السلامة العامة والوقاية من الحوادث (عام)
  {
    id: 'GEN-08-01',
    axis: 'السلامة العامة والوقاية من الحوادث',
    category: 'سلامة',
    criteria: 'توفر تجهيزات مكافحة الحريق (مطفآت، صنابير حريق...) في حالة عمل وبعدد ومواقع مناسبة لطبيعة المنشأة.',
    legalReference: 'القانون 19-02 المتعلق بالقواعد العامة للوقاية من أخطار الحريق والفزع + النصوص التطبيقية.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-08-02',
    axis: 'السلامة العامة والوقاية من الحوادث',
    category: 'سلامة',
    criteria: 'مسارات الإخلاء خالية من العوائق ومخارج الطوارئ تفتح نحو الخارج ومشار إليها بوضوح.',
    legalReference: 'القانون 19-02.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'GEN-08-03',
    axis: 'السلامة العامة والوقاية من الحوادث',
    category: 'سلامة',
    criteria: 'تخزين آمن للمواد الكيميائية (منظفات، مبيدات، محروقات) بعيدًا عن مصادر الحرارة وبعبوات موسومة بوضوح.',
    legalReference: 'القانون 03-10 (المواد الخطرة) + 01-19 (النفايات الخاصة الخطرة).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];