// src/baseFoodCriteria.ts
import { InspectionItem } from '../types';

export const baseFoodCriteria: InspectionItem[] = [
  // المحور 1 (إضافي) – الاعتماد الصحي والتراخيص الغذائية
  {
    id: 'BFD-01-01',
    axis: 'الاعتماد الصحي والتراخيص',
    category: 'تنظيمية',
    criteria: 'الاعتماد الصحي أو الترخيص الصحي عند الاقتضاء في الأنشطة الغذائية.',
    legalReference: 'المرسوم التنفيذي 17-140 المتعلق بشروط النظافة والنظافة الصحية في المؤسسات الغذائية.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 5: تجهيزات حفظ وتحضير الأغذية
  {
    id: 'BFD-05-01',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحيه',
    criteria: 'توفر ثلاجات وغرف تبريد مزودة بميزان حرارة داخلي مقروء.',
    legalReference: 'المرسوم 17-140 + أدلة GHP/القرار الوزاري المشترك 2020 المتعلق بـ HACCP.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-02',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحيه',
    criteria: 'حفظ الأغذية المبردة في درجة حرارة بين 0 و 5°م حسب طبيعة المنتوج.',
    legalReference: 'المرسوم 17-140 + القرارات الوزارية الخاصة بالتخزين البارد.',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: '°C',
      labelAr: 'درجة حرارة الثلاجة (أغذية مبردة)',
      min: 0,
      max: 5,
      warningMax: 7,
      step: 0.1,
    },
  },
  {
    id: 'BFD-05-03',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحيه',
    criteria: 'حفظ الأغذية المجمدة في درجة حرارة -18°م أو أقل.',
    legalReference: 'القراراد الوزارية المتعلقة بالتجميد.',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: '°C',
      labelAr: 'درجة حرارة الفريزر (أغذية مجمدة)',
      min: -100,
      max: -18,
      warningMax: -15,
      step: 0.5,
      upperLimit: true,
    },
  },
  {
    id: 'BFD-05-04',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحيه',
    criteria: 'فصل واضح بين المواد الأولية والمنتجات الجاهزة في التحضير والتخزين لتجنب التلوث المتبادل.',
    legalReference: 'المرسوم 17-140 + مبادئ HACCP.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-05',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحيه',
    criteria: 'أسطح تحضير ملساء، غير منفذة، غير سامة، سهلة التطهير.',
    legalReference: 'المرسوم 17-140.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-06',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحيه',
    criteria: 'توفر الماء الساخن للغسل في مناطق التحضير والتنظيف.',
    legalReference: 'المرسوم 17-140.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-05-07',
    axis: 'تجهيزات الحفظ والتحضير',
    category: 'صحيه',
    criteria: 'تنظيف المعدات وفق تسلسل: غسل – شطف – تعقيم – تجفيف، مع توثيق عند الاقتضاء.',
    legalReference: 'المرسوم 17-140 + أدلة GHP.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // المحور 6: صحة وسلوك العمال (مع تفاصيل غذائية)
  {
    id: 'BFD-06-01',
    axis: 'صحة وسلوك العمال',
    category: 'صحيه',
    criteria: 'ارتداء لباس عمل نظيف، وأغطية رأس، ووسائل وقاية شخصية حسب طبيعة المهام.',
    legalReference: 'المرسوم 17-140.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-06-02',
    axis: 'صحة وسلوك العمال',
    category: 'صحيه',
    criteria: 'توفر أحواض غسل اليدين بالصابون والماء الدافئ ومناشف أحادية الاستعمال قرب مناطق العمل.',
    legalReference: 'المرسوم 17-140.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-06-03',
    axis: 'صحة وسلوك العمال',
    category: 'صحيه',
    criteria: 'إخضاع العمال لفحص طبي قبل التوظيف وفحوصات طبية دورية (كل 6 أشهر في قطاع الأغذية).',
    legalReference: 'القانون 18-11 + المراسيم التطبيقية.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-06-04',
    axis: 'صحة وسلوك العمال',
    category: 'صحيه',
    criteria: 'منع الأكل والشرب والتدخين والبصق في أماكن تداول الأغذية والعمل الإنتاجي.',
    legalReference: 'المرسوم 17-140.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // مكافحة النواقل إضافية للغذاء
  {
    id: 'BFD-07-01',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'تركيب شبكات معدنية (شباك) على النوافذ والفتحات المطلة على الخارج، سهلة النزع للتنظيف.',
    legalReference: 'المرسوم 17-140.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BFD-07-02',
    axis: 'مكافحة النواقل',
    category: 'نظافة',
    criteria: 'إعداد خريطة مراقبة للقوارض والحشرات مع متابعة دورية.',
    legalReference: 'ممارسات GHP/HACCP.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
