import { InspectionItem } from '../types';
import { baseCompressedGasCriteria } from './baseCompressedGasCriteria';

export const blacksmithCriteria: InspectionItem[] = [
  // BLS-01-01 removed — fully covered by BGN-01-01 (baseGeneralCriteria)
  {
    id: 'BLS-02-01',
    axis: 'الموقع والتهيئة',
    category: 'بيئية',
    criteria: 'عدم تجاوز مستوى الضجيج المرجعي (لا يتجاوز 70 ديسيبل في المحيط الحضري) لتفادي الإضرار بالجوار.',
    legalReference: 'القانون 03-10 (حماية البيئة وراحة الجوار) + المرسوم 93-120.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-02-02',
    axis: 'الموقع والتهيئة',
    category: 'بيئية',
    criteria: 'عدم إشغال الطريق العام بالمواد أو الآلات أو أجزاء معدنية.',
    legalReference: 'القانون 03-10.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-03-01',
    axis: 'النفايات المعدنية',
    category: 'بيئية',
    criteria: 'جمع نفايات المعدن والشظايا في حاويات مخصصة، وتسليمها لمتعامل معتمد أو مرفق جمع معتمد.',
    legalReference: 'القانون 01-19 (تسيير النفايات) + المرسوم 09-19 (اعتماد متعاملي النفايات).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-04-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية للعمال: نظارات وقاية، قفازات واقية، سماعات واقية للضجيج، وواقية وجه عند اللحام.',
    legalReference: 'القانون 90-11 + المرسوم 93-120 (وسائل الوقاية الشخصية الملزمة في الأنشطة ذات المخاطر).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // BLS-04-02 removed — replaced by shared baseCompressedGasCriteria (CGS-01-01, CGS-01-02, CGS-01-03)
  ...baseCompressedGasCriteria,
  {
    id: 'BLS-04-03',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'سلامة التركيبات الكهربائية: أسلاك سليمة، تأريض مناسب للجهاز الكهربائي وأجهزة اللحام، لا توجد أسلاك عارية ظاهرة.',
    legalReference: 'المرسوم 76-35 (اشتراطات حماية العمال الكهربائية) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 6.5: split — extinguisher service-tag check only (exits covered by BGN-08-02)
    id: 'BLS-04-04',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق واحدة على الأقل (نوع بودرة ABC أو CO2 مناسب لبيئة اللحام والمعادن) بحالة صالحة، مع التحقق من بطاقة الصيانة السنوية لكل مطفأة (تاريخ آخر فحص وتاريخ انتهاء الصلاحية).',
    legalReference: 'القانون 19-02 المادة 7 (تجهيزات الإطفاء الأولية في المنشآت الصناعية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 9.2: machine-guard criterion for rotating cutting/grinding equipment
    id: 'BLS-04-05',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر حمايات ميكانيكية (واقيات) على أجهزة القطع والجلخ الدوارة (جلخة، مقطع معدني) لمنع التماس مع الأجزاء المتحركة، مع وجود أزرار إيقاف طارئ في متناول المشغّل.',
    legalReference: 'القانون 90-11 + المرسوم 93-120 (اشتراطات حماية الآلات الدوارة وأزرار الإيقاف الطارئ).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-04-06',
    axis: 'السلامة المهنية',
    category: 'بيئية',
    criteria: 'إجراء قياس مستوى الضجيج في بيئة العمل بصفة دورية (جهاز قياس معتمد)، والتحقق من عدم تجاوز الحد الأقصى المسموح به (85 ديسيبل)؛ وفي حال التجاوز، توثيق الإجراءات التصحيحية المتخذة.',
    legalReference: 'المرسوم 93-120 (الحد الأقصى للضجيج في بيئة العمل: 85 ديسيبل) + القانون 90-11.',
    severity: 'medium',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      label: 'مستوى الضجيج المقاس (ديسيبل)',
      unit: 'dB',
      threshold: 85,
      comparisonOperator: 'lte',
    },
  },
  {
    id: 'BLS-05-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'إجراء فحوصات طبية دورية للعمال المعرضين للضجيج المفرط والأبخرة المعدنية.',
    legalReference: 'المرسوم 93-120 (الفحص الطبي الدوري للأنشطة ذات المخاطر المهنية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
