import { InspectionItem } from '../types';

export const blacksmithCriteria: InspectionItem[] = [
  {
    id: 'BLS-30-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط حدادة، أو معاينة عدمها مع الإشارة إلى مخالفة تنظيم المؤسسات المصنفة.',
    legalReference: 'المرسوم 06-198 (تصنيف المنشآت ورخصة الاستغلال).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-30-02',
    axis: 'الضجيج والاهتزازات',
    category: 'بيئية',
    criteria: 'عدم تجاوز مستوى الضجيج المرجعي (لا يتجاوز 70 ديسيبل في المحيط الحضري) لتفادي الإضرار بالجوار.',
    legalReference: 'القانون 03-10 (حماية البيئة وراحة الجوار) + المرسوم 93-120 (طب العمل، حد الضجيج في محيط العمل).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-30-03',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية للعمال: نظارات وقاية، قفازات واقية، سماعات واقية للضجيج، وواقية وجه عند اللحام.',
    legalReference: 'القانون 90-11 (سلامة العمال) + المرسوم 93-120 (وسائل الوقاية الشخصية الملزمة في الأنشطة ذات المخاطر).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-30-04',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'سلامة التركيبات الكهربائية: أسلاك سليمة، تأريض مناسب للجهاز الكهربائي وأجهزة اللحام، لا توجد أسلاك عارية ظاهرة.',
    legalReference: 'المرسوم 76-35 (اشتراطات حماية العمال الكهربائية) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-30-05',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق واحدة على الأقل بحالة صالحة ومخارج طوارئ واضحة التسمية.',
    legalReference: 'القانون 19-02 (الوقاية من الحريق).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'BLS-30-06',
    axis: 'البيئة والنفايات',
    category: 'بيئية',
    criteria: 'جمع نفايات المعدن والشظايا في حاويات مخصصة، وتسليمها لمتعامل معتمد أو مرفق جمع معتمد.',
    legalReference: 'القانون 01-19 (تسيير النفايات) + المرسوم 09-19 (اعتماد متعاملي النفايات).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
