import { InspectionItem } from '../types';

export const carpenteryCriteria: InspectionItem[] = [
  {
    id: 'CRP-31-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط نجارة، أو معاينة اشتغالها بدون ترخيص.',
    legalReference: 'المرسوم 06-198 (تصنيف المنشآت ورخصة الاستغلال).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-31-02',
    axis: 'التهوية وغبار الخشب',
    category: 'بيئية',
    criteria: 'توفر تهوية كافية (ميكانيكية أو طبيعية) ونظام سحب غبار فعال (شفاط سير + منخل ترشيح) للحد من تعرض العمال لغبار الخشب.',
    legalReference: 'المرسوم 93-120 (حماية العمال من غبار الخشب) + القانون 90-11 (السلامة المهنية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-31-03',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية: واقي أذنين (SPP أو FFP2) ضد غبار الخشب، نظارات وقاية، قفازات، واقي بدن لأجهزة الدوارة.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-31-04',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'توفر مطفآت حريق بحالة صالحة (بطاقة صيانة خلال الـ 12 شهرا الأخيرة) ومخارج طوارئ واضحة، وحظر التدخين داخل الورشة.',
    legalReference: 'القانون 19-02 (الوقاية من الحريق في المحال للمواد القابلة للاشتعال).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-31-05',
    axis: 'البيئة والنفايات',
    category: 'بيئية',
    criteria: 'جمع بقايا الخشب ونشارة الخشب في حاويات مخصصة وعدم إحراقها في الهواء الطلق، ونقلها لمرافق الجمع المعتمدة.',
    legalReference: 'القانون 01-19 (حظر الحرق في الهواء الطلق) + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
