import { InspectionItem } from '../types';

export const carpenteryCriteria: InspectionItem[] = [
  {
    id: 'CAR-01-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط نجارة، أو معاينة اشتغالها بدون ترخيص.',
    legalReference: 'المرسوم 06-198 (تصنيف المنشآت ورخصة الاستغلال).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-02-01',
    axis: 'الموقع والتهيئة',
    category: 'بيئية',
    criteria: 'توفر تهوية كافية (ميكانيكية أو طبيعية) ونظام سحب غبار فعال (شفاط سير + منخل ترشيح) للحد من تعرض العمال لغبار الخشب.',
    legalReference: 'المرسوم 93-120 (حماية العمال من غبار الخشب) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-02-02',
    axis: 'الموقع والتهيئة',
    category: 'بيئية',
    criteria: 'عدم تجاوز مستوى الضجيج المرجعي داخل الورشة (لا يتجاوز 85 ديسيبل في بيئة العمل) وعدم الإضرار بالجوار، مع إجراء قياس دوري للضوضاء عند الاقتضاء.',
    legalReference: 'المرسوم 93-120 (الحد الأقصى للضجيج في أماكن العمل) + القانون 03-10 (راحة الجوار).',
    severity: 'medium',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-03-01',
    axis: 'نفايات الخشب والألمنيوم',
    category: 'بيئية',
    criteria: 'جمع بقايا الخشب ونشارة الخشب في حاويات مخصصة ونقلها لمرافق الجمع المعتمدة.',
    legalReference: 'القانون 01-19 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-03-02',
    axis: 'نفايات الخشب والألمنيوم',
    category: 'بيئية',
    criteria: 'حظر حرق نفايات الخشب والمواد البلاستيكية في الهواء الطلق.',
    legalReference: 'القانون 01-19 (حظر الحرق في الهواء الطلق) + القانون 03-10.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-03-03',
    axis: 'نفايات الخشب والألمنيوم',
    category: 'بيئية',
    criteria: 'جمع بقايا الألمنيوم في حاويات مخصصة وتسليمها لمتعامل معتمد.',
    legalReference: 'القانون 01-19 + المرسوم 09-19.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-04-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية: واقي أذنين ضد غبار الخشب (FFP2)، نظارات وقاية، قفازات.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-04-02',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر حمايات ميكانيكية (واقيات) على أجهزة القطع الدوارة (منشار دائري، جلخ) لمنع الحوادث، مع وجود أزرار إيقاف طارئ في متناول المشغّل.',
    legalReference: 'القانون 90-11 + المرسوم 93-120 (اشتراطات حماية الآلات الدوارة وأزرار الإيقاف الطارئ).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-04-03',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفآت حريق بحالة صالحة مع التحقق من بطاقة الصيانة السنوية لكل مطفأة (تاريخ آخر فحص وتاريخ انتهاء الصلاحية)، وحظر التدخين داخل الورشة.',
    legalReference: 'القانون 19-02 (الوقاية من الحريق في المحال للمواد القابلة للاشتعال).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CAR-05-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'مخارج الطوارئ خالية من العوائق، مشار إليها بوضوح، وتفتح نحو الخارج.',
    legalReference: 'القانون 19-02 (مخارج الطوارئ ومسارات الإخلاء).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
