import { InspectionItem } from '../types';

export const carpenteryCriteria: InspectionItem[] = [
  // CRP-01-01 removed — pure restate of BGN-01-01 (operating license, generic). No unique content added.
  {
    id: 'CRP-01-02',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية المفعول.',
    legalReference: 'القانون 04-08 (الشروط العامة لممارسة الأنشطة التجارية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-02-01',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'توفر نظام شفط وتجميع نشارة الخشب وغبار الخشب (سيكلون أو مرشح كيسي) فعال ومتصل بجميع الآلات الخاشبة.',
    legalReference: 'القانون 03-10 + المرسوم 06-138 (ينظّم انبعاث الغاز والدخان والبخار والجزيئات في الجو من المنشآت الصناعية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-02-02',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'عدم إطلاق غبار الخشب مباشرة في الهواء الخارجي دون معالجة أو ترشيح، والتحقق من سلامة مخارج نظام الشفط.',
    legalReference: 'المرسوم 06-138 (التزامات الحد من الانبعاثات الهوائية الصناعية عند المصدر).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase A: total dust stack-emission measurement — Décret 06-138 Annex I general limit 50 mg/Nm³.
    // Wood dust is predominantly nuisance/coarse dust; the 50 mg/Nm³ Annex I general limit applies.
    id: 'CRP-07-01',
    axis: 'الانبعاثات الهوائية',
    category: 'بيئية',
    criteria: 'إجراء قياس دوري لتركيز الغبار الكلي (poussières totales) في الانبعاثات الهوائية عند نقطة مصب نظام الشفط (مرة في السنة على الأقل) بواسطة مختبر معتمد، والتحقق من عدم تجاوز القيمة الحدية (50 ملغ/م³ن للحد العام)؛ وتوثيق نتائج القياسات والإجراءات التصحيحية عند الاقتضاء.',
    legalReference: 'القانون 03-10 المادة 52 + المرسوم 06-138 الملحق I (الغبار الكلي ≤ 50 ملغ/م³ن — الحد العام للمنشآت الصناعية).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/Nm³',
      labelAr: 'تركيز الغبار الكلي عند نقطة المصب',
      max: 50,
      warningMax: 40,
      step: 1,
      upperLimit: true,
    },
  },
  {
    // Phase A: records retention ≥ 3 years — Décret 06-138 Art. 11
    id: 'CRP-07-02',
    axis: 'الانبعاثات الهوائية',
    category: 'تنظيمية',
    criteria: 'الاحتفاظ بسجلات نتائج القياسات الدورية للانبعاثات الهوائية (الغبار الكلي) مدة لا تقل عن 3 سنوات وإتاحتها للمفتش عند الطلب.',
    legalReference: 'المرسوم 06-138 المادة 11 (إلزامية الاحتفاظ بسجلات القياسات الدورية للانبعاثات الهوائية لمدة ثلاث سنوات على الأقل).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-03-01',
    axis: 'تسيير النفايات',
    category: 'بيئية',
    criteria: 'جمع نشارة الخشب وبقايا القطع في حاويات مخصصة وعدم حرقها في الهواء الطلق.',
    legalReference: 'القانون 01-19 + المرسوم 09-19 (حظر الحرق المكشوف للنفايات).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-04-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر واقيات على الآلات الدوارة والمناشير الدائرية، مع وجود أزرار إيقاف طارئ في متناول المشغّل.',
    legalReference: 'القانون 90-11 + المرسوم 93-120 (اشتراطات حماية الآلات الدوارة وأزرار الإيقاف الطارئ).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-04-02',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية: كمامات من غبار الخشب (FFP2 على الأقل)، واقٍ للعينين، واقٍ للسمع عند الأعمال الصوتية.',
    legalReference: 'القانون 90-11 المادة 8 + المرسوم 93-120.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CRP-04-03',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق واحدة على الأقل بحالة صالحة مع التحقق من بطاقة الصيانة السنوية (تاريخ آخر فحص وتاريخ انتهاء الصلاحية)، ومخارج طوارئ واضحة التسمية خالية من العوائق.',
    legalReference: 'القانون 19-02 (الوقاية من الحريق في الورش التي تحتوي على مواد خشبية قابلة للاشتعال).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
