import { InspectionItem } from '../types';

export const carWashCriteria: InspectionItem[] = [
  {
    id: 'CWS-34-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط غسيل السيارات.',
    legalReference: 'المرسوم 06-198.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-34-02',
    axis: 'المياه والصرف',
    category: 'بيئية',
    criteria: 'وجود فاصل زيوت وشحوم (décanteur/séparateur d’huile) فعال قبل تصريف مياه الغسيل إلى شبكة الصرف الصحي.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للمصبات السائلة في شبكة الصرف).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-34-03',
    axis: 'المياه والصرف',
    category: 'بيئية',
    criteria: 'ترشيح وإعادة استخدام مياه الغسيل بعد التصفية لتقليل استهلاك الماء، أو توثيق كمية الماء المستهلكة لكل سيارة.',
    legalReference: 'القانون 03-10 (ترشيد استهلاك الموارد المائية).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-34-04',
    axis: 'النفايات والتنظيف',
    category: 'بيئية',
    criteria: 'جمع الحمأة المستخرجة من الفاصل وتسليمها لمتعامل معتمد وفق المرسوم 09-19، وعدم طرحها في التربة.',
    legalReference: 'القانون 01-19 + المرسوم 93-162 (نفايات الزيوت والشحوم).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-34-05',
    axis: 'السلامة',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق ومخارج طوارئ واضحة.',
    legalReference: 'القانون 19-02.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
