import { InspectionItem } from '../types';

export const carWashCriteria: InspectionItem[] = [
  {
    id: 'CWS-01-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط غسيل السيارات.',
    legalReference: 'المرسوم 06-198.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-01-02',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية المفعول.',
    legalReference: 'القانون 04-08.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-02-01',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'وجود فاصل زيوت وشحوم (décanteur/séparateur d'huile) فعال قبل تصريف مياه الغسيل إلى شبكة الصرف الصحي.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للمصبات السائلة في شبكة الصرف).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-02-02',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'ترشيح وإعادة استخدام مياه الغسيل بعد التصفية لتقليل استهلاك الماء، أو توثيق كمية الماء المستهلكة لكل سيارة.',
    legalReference: 'القانون 03-10 (ترشيد استهلاك الموارد المائية).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-02-03',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'وجود أرضية مجهزة بتجميع المياه لمنع التسرب المباشر إلى التربة أو الطريق.',
    legalReference: 'القانون 03-10 + المرسوم 06-141.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-02-04',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'جمع الحمأة المستخرجة من الفاصل وتسليمها لمتعامل معتمد وفق المرسوم 09-19، وعدم طرحها في التربة.',
    legalReference: 'القانون 01-19 + المرسوم 93-162 (نفايات الزيوت والشحوم).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-03-01',
    axis: 'المواد الكيميائية',
    category: 'بيئية',
    criteria: 'تخزين مواد الغسيل الكيميائية (الشامبو، الشمع، المنظفات) في مخزن مغلق ومهوى مع بطاقات التعريف على كل عبوة.',
    legalReference: 'القانون 03-10 + المرسوم 05-315.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-03-02',
    axis: 'المواد الكيميائية',
    category: 'بيئية',
    criteria: 'عدم استخدام مواد كيميائية محظورة أو غير مرخصة في عمليات الغسيل.',
    legalReference: 'القانون 03-10.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-04-01',
    axis: 'النظافة والسلامة',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق ومخارج طوارئ واضحة.',
    legalReference: 'القانون 19-02.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-04-02',
    axis: 'النظافة والسلامة',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية للعمال (قفازات مقاومة للمواد الكيميائية، أحذية واقية) وتدريبهم على التعامل مع المواد الكيميائية.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
