import { InspectionItem } from '../types';

export const carWashCriteria: InspectionItem[] = [
  // CWS-01-01 removed — pure restate of BGN-01-01 (operating license, generic). BGN-01-01 already covers نوع النشاط.
  {
    id: 'CWS-01-02',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية المفعول.',
    legalReference: 'القانون 04-08.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 4.1 — added numericField for hydrocarbons threshold in carwash effluent (المرسوم 06-141)
    id: 'CWS-02-01',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: "وجود فاصل زيوت وشحوم (décanteur/séparateur d'huile) فعال قبل تصريف مياه الغسيل إلى شبكة الصرف الصحي. قياس تركيز الهيدروكربونات في المياه المصرَّفة والتحقق من عدم تجاوز القيمة القصوى المحددة تنظيمياً (10 ملغ/ل).",
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للمصبات السائلة الصناعية — الهيدروكربونات ≤ 10 ملغ/ل).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'تركيز الهيدروكربونات عند نقطة التصريف',
      max: 10,
      warningMax: 8,
      step: 0.5,
      upperLimit: true,
    },
  },
  {
    // Tier2-Ch1: pH — Décret 06-141 Annex I (6.5–8.5) — general discharge standard
    id: 'CWS-02-01B',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'قياس درجة حموضة (pH) مياه التصريف عند نقطة التصريف والتحقق من امتثالها للقيمة القصوى المحددة في التنظيم (6.5 – 8.5).',
    legalReference: 'المرسوم التنفيذي 06-141 الملحق I (pH: 6.5–8.5).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'pH',
      labelAr: 'درجة حموضة مياه التصريف',
      min: 6.5,
      max: 8.5,
      warningMin: 6.8,
      warningMax: 8.2,
      step: 0.1,
    },
  },
  {
    // Tier2-Ch1: MES — Décret 06-141 Annex I ≤ 35 mg/L
    id: 'CWS-02-01C',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'قياس المواد العالقة الكلية (MES) في مياه التصريف والتحقق من عدم تجاوز القيمة القصوى (35 ملغ/ل).',
    legalReference: 'المرسوم التنفيذي 06-141 الملحق I (MES: ≤ 35 ملغ/ل).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'المواد العالقة الكلية (MES)',
      max: 35,
      warningMax: 28,
      step: 1,
      upperLimit: true,
    },
  },
  {
    // Tier2-Ch1: BOD5 — Décret 06-141 Annex I ≤ 35 mg/L
    id: 'CWS-02-01D',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'قياس الطلب البيولوجي على الأكسجين (DBO5) في مياه التصريف والتحقق من عدم تجاوز القيمة القصوى (35 ملغ/ل).',
    legalReference: 'المرسوم التنفيذي 06-141 الملحق I (DBO5: ≤ 35 ملغ/ل).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'الطلب البيولوجي على الأكسجين (DBO5)',
      max: 35,
      warningMax: 28,
      step: 1,
      upperLimit: true,
    },
  },
  {
    // Tier2-Ch1: COD — Décret 06-141 Annex I ≤ 120 mg/L
    id: 'CWS-02-01E',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'قياس الطلب الكيميائي على الأكسجين (DCO) في مياه التصريف والتحقق من عدم تجاوز القيمة القصوى (120 ملغ/ل).',
    legalReference: 'المرسوم التنفيذي 06-141 الملحق I (DCO: ≤ 120 ملغ/ل).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'الطلب الكيميائي على الأكسجين (DCO)',
      max: 120,
      warningMax: 96,
      step: 1,
      upperLimit: true,
    },
  },
  {
    id: 'CWS-02-02',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'ترشيح وإعادة استخدام مياه الغسيل بعد التصفية لتقليل استهلاك الماء، أو توثيق كمية الماء المستهلكة لكل سيارة.',
    legalReference: 'القانون 03-10 (ترشيد استهلاك الموارد المائية).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-02-03',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'وجود أرضية مجهزة بتجميع المياه لمنع التسرب المباشر إلى التربة أو الطريق.',
    legalReference: 'القانون 03-10 + المرسوم 06-141.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-02-04',
    axis: 'تسيير مياه الغسل',
    category: 'بيئية',
    criteria: 'جمع الحمأة المستخرجة من الفاصل وتسليمها لمتعامل معتمد وفق المرسوم 09-19، وعدم طرحها في التربة.',
    legalReference: 'القانون 01-19 + المرسوم 93-162 (نفايات الزيوت والشحوم).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 4.3 — discharge permit for car wash (new criterion)
    id: 'CWS-02-05',
    axis: 'تسيير مياه الغسل',
    category: 'تنظيمية',
    criteria: 'الحصول على رخصة تصريف صناعي من مديرية الموارد المائية قبل التصريف في الشبكة العمومية، واحترام شروطها من حيث نقاط التصريف والقيم الحدودية للهيدروكربونات والمواد العالقة والمنظفات.',
    legalReference: 'القانون 05-12 المتعلق بالمياه (المادة 46: حظر التلوث) + المرسوم 06-141 (القيم القصوى للمصبات الصناعية) + التنظيم المتعلق برخص التفريغ الصادرة عن مصالح الموارد المائية.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-03-01',
    axis: 'المواد الكيميائية',
    category: 'بيئية',
    criteria: 'استخدام مواد تنظيف قابلة للتحلل البيولوجي ومرخصة بيئياً وتخزينها في مخزن مهوى بعيداً عن مصادر الاشتعال.',
    legalReference: 'القانون 03-10.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-03-02',
    axis: 'المواد الكيميائية',
    category: 'بيئية',
    criteria: 'حظر تصريف مياه الغسيل الملوثة بالمواد الكيميائية مباشرة في الطريق العام أو التربة دون معالجة.',
    legalReference: 'القانون 03-10 + المرسوم 06-141.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-03-03',
    axis: 'المواد الكيميائية',
    category: 'بيئية',
    criteria: 'تسجيل استهلاك مواد التنظيف وتتبع كمية المواد الكيميائية المستخدمة لضمان عدم الإفراط.',
    legalReference: 'القانون 03-10 (ترشيد استهلاك المواد الكيميائية).',
    severity: 'low',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    // Tier2-Ch1 fix: replaced Décret 93-120 (periodic medical exams, NOT PPE).
    // Correct basis: Décret 91-05 art.9 (employer PPE obligation) + Décret 02-427 (PPE training).
    id: 'CWS-04-01',
    axis: 'النظافة والسلامة',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية للعمال (قفازات مقاومة للكيماويات، أحذية واقية، ملابس عمل).',
    legalReference: 'المرسوم التنفيذي 91-05 المادة 9 (إلزامية توفير وسائل الوقاية الشخصية من طرف صاحب العمل) + المرسوم التنفيذي 02-427 (تدريب العمال على استخدام وسائل الوقاية الشخصية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-04-02',
    axis: 'النظافة والسلامة',
    category: 'سلامة',
    criteria: 'التعاقد مع مؤسسة معتمدة لجمع ونقل النفايات الخطرة الناتجة عن الغسيل.',
    legalReference: 'المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'CWS-05-01',
    axis: 'النظافة والسلامة',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق صالحة للاستعمال مع التحقق من بطاقة الصيانة السنوية لكل مطفأة (تاريخ آخر فحص وتاريخ انتهاء الصلاحية).',
    legalReference: 'القانون 19-02 (الوقاية من الحريق).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
