import { InspectionItem } from '../types';

export const marbleCriteria: InspectionItem[] = [
  {
    id: 'MRB-32-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط قطع وتشكيل الرخام/الجرانيت.',
    legalReference: 'المرسوم 06-198.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-32-02',
    axis: 'غبار السيليكا والتهوية',
    category: 'بيئية',
    criteria: 'توفر تهوية فعالة ونظام سحب غبار (شفاط سير + منخل مرشح) للحد من التعرض لغبار السيليكا المسبب للسحار.',
    legalReference: 'المرسوم 93-120 (حماية العمال من الأمراض المهنية ومنها السحار) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-32-03',
    axis: 'غبار السيليكا والتهوية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية: كمامات بخارية FFP2 أو جهاز تنفس خارجي، نظارات، قفازات، واقي سمعي عند القطع بالفلينسة.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-32-04',
    axis: 'المياه والصرف',
    category: 'بيئية',
    criteria: 'تصريف مياه القطع والتشكيل إلى شبكة الصرف الصحي عبر حوض ترسيب، وعدم تصريفها مباشرة في الطريق.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للمصبات الصناعية).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-32-05',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق ومخارج طوارئ واضحة وحمايات ميكانيكية على أجهزة القطع.',
    legalReference: 'القانون 19-02 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
