import { InspectionItem } from '../types';

export const marbleCriteria: InspectionItem[] = [
  {
    id: 'MRB-01-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط قطع وتشكيل الرخام/الجرانيت.',
    legalReference: 'المرسوم 06-198.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-02-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية.',
    legalReference: 'القانون 04-08 (الشروط العامة لممارسة الأنشطة التجارية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-03-01',
    axis: 'المياه المستعملة والغبار',
    category: 'بيئية',
    criteria: 'توفر تهوية فعالة ونظام سحب غبار (شفاط سير + منخل مرشح) للحد من التعرض لغبار السيليكا المسبب للسحار.',
    legalReference: 'المرسوم 93-120 (حماية العمال من الأمراض المهنية) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-03-02',
    axis: 'المياه المستعملة والغبار',
    category: 'بيئية',
    criteria: 'تصريف مياه القطع والتشكيل إلى شبكة الصرف الصحي عبر حوض ترسيب، وعدم تصريفها مباشرة في الطريق.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للمصبات الصناعية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-04-01',
    axis: 'المياه المستعملة والغبار',
    category: 'بيئية',
    criteria: 'جمع الحمأة والمخلفات الصلبة من قطع الرخام في حاويات مخصصة وتسليمها لمتعامل معتمد.',
    legalReference: 'القانون 01-19 + المرسوم 09-19.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-05-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية: كمامات بخارية FFP2 أو جهاز تنفس خارجي، نظارات، قفازات، واقي سمعي عند القطع بالفلينسة.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-05-02',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق ومخارج طوارئ واضحة وحمايات ميكانيكية على أجهزة القطع.',
    legalReference: 'القانون 19-02 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-05-03',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'إجراء فحوصات طبية دورية للعمال المعرضين لغبار السيليكا.',
    legalReference: 'المرسوم 93-120 (الفحص الطبي الدوري للأنشطة ذات المخاطر المهنية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
