import { InspectionItem } from '../types';

export const marbleCriteria: InspectionItem[] = [
  // MRB-01-01 removed — pure restate of BGN-01-01 (operating license, generic). No unique content added.
  {
    id: 'MRB-02-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية.',
    legalReference: 'القانون 04-08 (الشروط العامة لممارسة الأنشطة التجارية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-02-02',
    axis: 'الموقع والتهيئة',
    category: 'بيئية',
    criteria: 'عدم تسبب الورشة في انتشار غبار الرخام خارج المنشأة وعدم إزعاج الجوار أو تلوث الطريق العام.',
    legalReference: 'القانون 03-10 + المرسوم 06-141.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-03-01',
    axis: 'المياه المستعملة والغبار',
    category: 'بيئية',
    criteria: 'توفر تهوية فعالة ونظام سحب غبار (شفاط سير + منخل مرشح) للحد من التعرض لغبار السيليكا المسبب للسحار.',
    legalReference: 'المرسوم 93-120 (حماية العمال من الأمراض المهنية) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 4.1 — added numericField for MES (suspended solids) threshold in cutting/shaping wastewater
    id: 'MRB-03-02',
    axis: 'المياه المستعملة والغبار',
    category: 'بيئية',
    criteria: 'تصريف مياه القطع والتشكيل إلى شبكة الصرف الصحي عبر حوض ترسيب، وعدم تصريفها مباشرة في الطريق. عند التصريف في الشبكة العمومية أو الوسط الطبيعي: قياس المواد العالقة (MES) عند نقطة التصريف والتحقق من عدم تجاوز القيمة القصوى (35 ملغ/ل في الوسط الطبيعي).',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للمصبات الصناعية — MES ≤ 35 ملغ/ل في الوسط الطبيعي).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'MES (المواد العالقة) عند نقطة التصريف',
      max: 35,
      warningMax: 30,
      step: 1,
      upperLimit: true,
    },
  },
  {
    id: 'MRB-04-01',
    axis: 'المياه المستعملة والغبار',
    category: 'بيئية',
    criteria: 'جمع الحمأة والمخلفات الصلبة من قطع الرخام في حاويات مخصصة وتسليمها لمتعامل معتمد.',
    legalReference: 'القانون 01-19 + المرسوم 09-19.',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 4.3 — discharge permit for marble workshop (new criterion)
    id: 'MRB-04-02',
    axis: 'المياه المستعملة والغبار',
    category: 'تنظيمية',
    criteria: 'الحصول على رخصة تصريف صناعي من مديرية الموارد المائية (أو ما يعادلها) قبل التصريف في الشبكة العمومية أو الوسط الطبيعي، واحترام شروطها من حيث نقاط التصريف والقيم الحدودية للمواد العالقة والمواد الكيميائية.',
    legalReference: 'القانون 05-12 المتعلق بالمياه (المادة 46: حظر التلوث) + المرسوم 06-141 (القيم القصوى للمصبات الصناعية) + التنظيم المتعلق برخص التفريغ الصادرة عن مصالح الموارد المائية.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-05-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية: كمامات بخارية FFP2 أو جهاز تنفس خارجي، نظارات، قفازات، واقي سمعي عند القطع بالفلينسة.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-05-02',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق واحدة على الأقل بحالة صالحة مع التحقق من بطاقة الصيانة السنوية (تاريخ آخر فحص وتاريخ انتهاء الصلاحية)، ومخارج طوارئ واضحة التسمية خالية من العوائق.',
    legalReference: 'القانون 19-02 (الوقاية من الحريق).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-05-03',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'إجراء فحوصات طبية دورية للعمال المعرضين لغبار السيليكا.',
    legalReference: 'المرسوم 93-120 (الفحص الطبي الدوري للأنشطة ذات المخاطر المهنية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MRB-05-04',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر حمايات ميكانيكية (واقيات) على أجهزة القطع الدوارة (فلينسة، منشار رخام) مع وجود أزرار إيقاف طارئ في متناول المشغّل.',
    legalReference: 'القانون 90-11 + المرسوم 93-120 (اشتراطات حماية الآلات الدوارة وأزرار الإيقاف الطارئ).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
