import { InspectionItem } from '../types';

export const mechanicWorkshopCriteria: InspectionItem[] = [
  {
    id: 'MCH-29-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة أو تصريح استغلال لنشاط ميكانيك سيارات، أو معاينة كونه يشتغل بدون أي ترخيص مع الإشارة إلى مخالفة تنظيم المؤسسات المصنفة.',
    legalReference: 'المرسوم التنفيذي 06-198 بشأن المؤسسات المصنفة والقانون 03-10 الذي يجرّم استغلال منشأة مصنفة دون ترخيص (المواد الجزائية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MCH-29-02',
    axis: 'الموقع والتهيئة',
    category: 'بيئية',
    criteria: 'عدم تسبب الورشة في إزعاج مفرط للجوار (ضجيج، تراكم سيارات في الطريق العام، انسكاب زيوت على الرصيف أو الطريق).',
    legalReference: 'القانون 03-10 الخاص بحماية البيئة والإطار المعيشي، الذي يلزم بتفادي الإضرار براحة الجوار والتلوث المرئي والضجيج.',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MCH-29-03',
    axis: 'النفايات الخطرة',
    category: 'بيئية',
    criteria: 'جمع الزيوت المستعملة وزيوت المحركات في حاويات محكمة ومانعة للتسرب وعدم طرحها في شبكة الصرف أو التربة أو المجرى العمومي.',
    legalReference: 'القانون 01-19 المتعلق بتسيير النفايات، والمرسوم التنفيذي 93-162 المتعلق باسترجاع الزيوت المستعملة ومعالجتها.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MCH-29-04',
    axis: 'النفايات الخطرة',
    category: 'بيئية',
    criteria: 'التعاقد مع مؤسسة معتمدة لجمع ونقل ومعالجة الزيوت المستعملة والفلاتر الملوثة وبقايا السوائل التقنية (فرامل، تبريد...).',
    legalReference: 'القانون 01-19 والمرسوم 05-315 الذي يحدد كيفيات التصريح بالنفايات الخاصة الخطرة ووجوب التعامل مع متعاملين معتمدين.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MCH-29-05',
    axis: 'المياه والصرف',
    category: 'بيئية',
    criteria: 'عدم طرح المياه الملوثة بالزيوت والشحوم مباشرة في شبكة الصرف الصحي أو الأمطار دون وجود فاصل زيوت أو نظام تجميع ومعالجة.',
    legalReference: 'القانون 03-10 بخصوص حماية المياه من التلوث والمرسوم 06-141 المتعلق بالقيم القصوى للتصريف في شبكات الصرف الصحي.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MCH-29-06',
    axis: 'النظافة والسلامة',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية للعمال (قفازات، نظارات، ملابس واقية).',
    legalReference: 'المرسوم 93-120 (وسائل الوقاية الشخصية) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'MCH-29-07',
    axis: 'النظافة والسلامة',
    category: 'سلامة',
    criteria: 'توفر مطفأة حريق بحالة صالحة مع التحقق من بطاقة الصيانة السنوية (تاريخ آخر فحص وتاريخ انتهاء الصلاحية)، ومخارج طوارئ خالية من العوائق وواضحة التسمية.',
    legalReference: 'القانون 19-02 (الوقاية من الحريق).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
