import { InspectionItem } from '../types';

export const paintShopCriteria: InspectionItem[] = [
  {
    id: 'PNT-01-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط دهن وورنيش سيارات.',
    legalReference: 'المرسوم 06-198.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-01-02',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية المفعول.',
    legalReference: 'القانون 04-08 (الشروط العامة لممارسة الأنشطة التجارية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-02-01',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'تهوية ميكانيكية فعالة في كابينة الدهان (تجفيف وتصفية البخار) وعدم إطلاق مذيبات عضوية (VOC) مباشرة في الهواء.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للانبعاثات الهوائية الصناعية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-02-02',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'توفر مرشحات هواء فعالة على منافذ الشفط وتسجيل دورات الصيانة.',
    legalReference: 'المرسوم 06-141.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-03-01',
    axis: 'تسيير النفايات الخطرة',
    category: 'بيئية',
    criteria: 'تجميع بقايا الدهان والمذيبات في حاويات مغلقة وموسومة وتسليمها لمتعامل معتمد وفق المرسوم 09-19.',
    legalReference: 'القانون 01-19 + المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-03-02',
    axis: 'تسيير النفايات الخطرة',
    category: 'بيئية',
    criteria: 'التعاقد مع مؤسسة معتمدة لجمع ونقل النفايات الخطرة الناتجة عن الدهان.',
    legalReference: 'المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-04-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية ملائمة (كمامات بخارية FFP2، نظارات وقاية، قفازات مقاومة للمذيبات) لعمال الدهان.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-04-02',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'حظر استخدام اللهب المكشوف أو التدخين داخل كابينة الدهان وحول منطقة تخزين المواد القابلة للاشتعال.',
    legalReference: 'القانون 19-02 (وقاية الحريق في المحال المتضمنة لمواد خطرة).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-05-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفآت حريق مناسبة للمواد الكيميائية (نوع بودرة ABC أو ثاني أكسيد الكربون CO2) ومخارج طوارئ واضحة.',
    legalReference: 'القانون 19-02.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
