import { InspectionItem } from '../types';

export const paintShopCriteria: InspectionItem[] = [
  // PNT-01-01 removed — pure restate of BGN-01-01 (operating license, generic). No unique content added.
  {
    id: 'PNT-01-02',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية المفعول.',
    legalReference: 'القانون 04-08 (الشروط العامة لممارسة الأنشطة التجارية).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-02-01',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'تهوية ميكانيكية فعالة في كابينة الدهان (تجفيف وتصفية البخار) وعدم إطلاق مذيبات عضوية (VOC) مباشرة في الهواء.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للانبعاثات الهوائية الصناعية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-02-02',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'توفر مرشحات هواء فعالة على منافذ الشفط وتسجيل دورات الصيانة.',
    legalReference: 'المرسوم 06-141.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 7.1: periodic VOC air quality measurement for paint shop
    id: 'PNT-02-03',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'إجراء قياس دوري لتركيز المركبات العضوية المتطايرة (VOC) في هواء بيئة العمل وعند نقطة المصب الهوائي (مرة في السنة على الأقل أو عند تغيير أنواع الدهانات المستخدمة) بواسطة مختبر معتمد، والتحقق من عدم تجاوز القيم الحدية المقررة؛ وتوثيق نتائج القياسات والإجراءات التصحيحية عند الاقتضاء.',
    legalReference: 'القانون 03-10 المادة 52 (التزام المنشآت المصنفة بمراقبة انبعاثاتها الهوائية) + المرسوم 06-141 (القيم القصوى للانبعاثات الهوائية الصناعية — VOC).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-03-01',
    axis: 'تسيير النفايات الخطرة',
    category: 'بيئية',
    criteria: 'تجميع بقايا الدهان والمذيبات في حاويات مغلقة وموسومة وتسليمها لمتعامل معتمد وفق المرسوم 09-19.',
    legalReference: 'القانون 01-19 + المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-03-02',
    axis: 'تسيير النفايات الخطرة',
    category: 'بيئية',
    criteria: 'التعاقد مع مؤسسة معتمدة لجمع ونقل النفايات الخطرة الناتجة عن الدهان.',
    legalReference: 'المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-04-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية ملائمة (كمامات بخارية FFP2، نظارات وقاية، قفازات مقاومة للمذيبات) لعمال الدهان.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-04-02',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'حظر استخدام اللهب المكشوف أو التدخين داخل كابينة الدهان وحول منطقة تخزين المواد القابلة للاشتعال.',
    legalReference: 'القانون 19-02 (وقاية الحريق في المحال المتضمنة لمواد خطرة).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 6.5: split — extinguisher type check only (exits covered by BGN-08-02)
    id: 'PNT-04-03',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفآت حريق مناسبة لبيئة المواد الكيميائية (نوع بودرة ABC أو ثاني أكسيد الكربون CO2 — الماء محظور في بيئة المذيبات) بحالة صالحة، مع التحقق من بطاقة الصيانة السنوية لكل مطفأة (تاريخ آخر فحص وتاريخ انتهاء الصلاحية). ملاحظة: الماء ممنوع لأنه ينشر المذيبات القابلة للاشتعال.',
    legalReference: 'القانون 19-02 المادة 7 (تجهيزات الإطفاء الأولية المناسبة لطبيعة المواد الخطرة).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
