import { InspectionItem } from '../types';

export const paintShopCriteria: InspectionItem[] = [
  {
    id: 'PNT-33-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط دهن وورنيش سيارات.',
    legalReference: 'المرسوم 06-198.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-33-02',
    axis: 'التهوية وانبعاثات المذيبات',
    category: 'بيئية',
    criteria: 'تهوية ميكانيكية فعالة في كابينة الدهان (تجفيف وتصفية البخار) وعدم إطلاق مذيبات عضوية (VOC) مباشرة في الهواء.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للانبعاثات الهوائية الصناعية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-33-03',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية ملائمة (كمامات بخارية FFP2، نظارات وقاية، قفازات مقاومة للمذيبات) لعمال الدهان.',
    legalReference: 'المرسوم 93-120 (وسائل الوقاية الشخصية للأنشطة ذات المخاطر الكيميائية) + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-33-04',
    axis: 'النفايات الخطرة',
    category: 'بيئية',
    criteria: 'تجميع بقايا الدهان والمذيبات في حاويات مغلقة وموسومة وتسليمها لمتعامل معتمد وفق المرسوم 09-19.',
    legalReference: 'القانون 01-19 + المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PNT-33-05',
    axis: 'السلامة من الحريق',
    category: 'سلامة',
    criteria: 'توفر مطفآت حريق مناسبة للمواد الكيميائية (نوع بودرة ABC أو ثاني أكسيد الكربون CO2) ومخارج طوارئ واضحة.',
    legalReference: 'القانون 19-02 (وقاية الحريق في المحال المتضمنة لمواد خطرة).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
