import { InspectionItem } from '../types';

export const printingCriteria: InspectionItem[] = [
  // PRT-01-01 removed — pure restate of BGN-01-01 (operating license, generic). No unique content added.
  {
    id: 'PRT-01-02',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر سجل تجاري أو وثيقة نشاط سارية المفعول.',
    legalReference: 'القانون 04-08.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-02-01',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'توفر تهوية ميكانيكية كافية وسحب بخار الحبر والمذيبات لمنع تراكمها في فضاء العمل.',
    legalReference: 'القانون 03-10 + المرسوم 06-138 (ينظّم انبعاث الغاز والدخان والبخار والجزيئات في الجو من المنشآت الصناعية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-02-02',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'عدم إطلاق بخار الحبر أو المذيبات العضوية مباشرة في الهواء الخارجي دون معالجة.',
    legalReference: 'المرسوم 06-138 (القيم القصوى للانبعاثات الهوائية الصناعية).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // Phase 7.1: periodic ink/solvent VOC air quality measurement for printing shop
    id: 'PRT-02-03',
    axis: 'التهوية ومنع التلوث الهوائي',
    category: 'بيئية',
    criteria: 'إجراء قياس دوري لتركيز المركبات العضوية المتطايرة (VOC) من أبخرة الأحبار والمذيبات في هواء بيئة العمل وعند نقطة المصب الهوائي (مرة في السنة على الأقل أو عند تغيير أنواع الأحبار أو المذيبات) بواسطة مختبر معتمد، والتحقق من عدم تجاوز القيم الحدية؛ وتوثيق نتائج القياسات والإجراءات التصحيحية عند الاقتضاء.',
    legalReference: 'القانون 03-10 المادة 52 (التزام المنشآت المصنفة بمراقبة انبعاثاتها الهوائية) + المرسوم 06-138 (القيم القصوى للانبعاثات الهوائية الصناعية — VOC).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-03-01',
    axis: 'تسيير النفايات الكيميائية',
    category: 'بيئية',
    criteria: 'جمع الأحبار المنتهية وعبوات المذيبات الفارغة في حاويات مغلقة وموسومة وتسليمها لمتعامل معتمد.',
    legalReference: 'القانون 01-19 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-03-02',
    axis: 'تسيير النفايات الكيميائية',
    category: 'بيئية',
    criteria: 'التعاقد مع مؤسسة معتمدة لجمع ونقل النفايات الخطرة الناتجة عن الطباعة.',
    legalReference: 'المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    // Fix: Décret 93-120 covers occupational medical exams only — not chemical storage.
    // Chemical storage safety → Décret 91-05 (hazardous substances at work) + Loi 88-07 (OHS general).
    id: 'PRT-03-03',
    axis: 'تسيير النفايات الكيميائية',
    category: 'بيئية',
    criteria: 'تخزين المواد الكيميائية في مخزن مغلق ومهوى بعيداً عن مصادر الاشتعال.',
    legalReference: 'القانون 19-02 (الوقاية من الحريق في مناطق تخزين المواد القابلة للاشتعال) + المرسوم التنفيذي 91-05 (الوقاية الصحية والأمن وطب العمل — اشتراطات تخزين المواد الخطرة) + القانون 88-07 المادة 9.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-04-01',
    axis: 'نفايات الورق والكرتون',
    category: 'بيئية',
    criteria: 'فرز ورق الطباعة المهدر وتسليمه لمراكز إعادة التدوير المعتمدة.',
    legalReference: 'القانون 01-19 (تثمين النفايات القابلة للتدوير).',
    severity: 'low',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    // Fix: Décret 93-120 covers occupational medical exams only — not PPE.
    // PPE obligation → Loi 90-11 Art. 8 (employer duty to provide PPE) + Décret 91-05 Art. 6.
    id: 'PRT-05-01',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية ملائمة: كمامات، نظارات وقاية، قفازات مقاومة للأحبار والمذيبات.',
    legalReference: 'القانون 90-11 المادة 8 (التزام صاحب العمل بتوفير وسائل الوقاية الشخصية الملائمة) + المرسوم التنفيذي 91-05 المادة 6 (الحد الأدنى من معدات الوقاية الشخصية في الأنشطة ذات المخاطر الكيميائية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    // Fix: Décret 93-120 covers occupational medical exams only — not machine guarding.
    // Machine guards → Loi 90-11 (OHS) + Décret 93-05 (equipment safety standards).
    id: 'PRT-05-02',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر حواجز وقائية على الآلات المتحركة (بكرات الطباعة، تجهيزات التقطيع) لمنع التماس مع الأجزاء الدوارة، مع وجود أزرار إيقاف طارئ في متناول المشغّل والتحقق من سلامة نظام القفل المانع (interlock) عند فتح الغطاء الواقي.',
    legalReference: 'القانون 90-11 (الوقاية الصحية والأمن وطب العمل — الالتزام العام بسلامة الآلات) + المرسوم التنفيذي 93-05 (اشتراطات السلامة التقنية للآلات الصناعية: الحمايات الميكانيكية وأزرار الإيقاف الطارئ ونظام القفل المانع).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-05-03',
    axis: 'السلامة المهنية',
    category: 'سلامة',
    criteria: 'توفر مطفآت حريق مناسبة للمواد الكيميائية القابلة للاشتعال مع التحقق من بطاقة الصيانة السنوية لكل مطفأة (تاريخ آخر فحص وتاريخ انتهاء الصلاحية).',
    legalReference: 'القانون 19-02 (الوقاية من الحريق في المحال التي تحتوي على مواد كيميائية قابلة للاشتعال).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
