import { InspectionItem } from '../types';

export const printingCriteria: InspectionItem[] = [
  {
    id: 'PRT-35-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط طباعة.',
    legalReference: 'المرسوم 06-198.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-35-02',
    axis: 'التهوية والانبعاثات',
    category: 'بيئية',
    criteria: 'تهوية كافية في الورشة للحد من أبخرة المذيبات العضوية (VOC) الصادرة من الأحبار ومواد التنظيف.',
    legalReference: 'القانون 03-10 + المرسوم 06-141 (القيم القصوى للانبعاثات الهوائية).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-35-03',
    axis: 'السلامة والوقاية',
    category: 'سلامة',
    criteria: 'توفر وسائل وقاية شخصية (كمامات وقاية للمذيبات، قفازات، واقي سمعي عند الحاجة) لعمال الطباعة.',
    legalReference: 'المرسوم 93-120 + القانون 90-11.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-35-04',
    axis: 'النفايات الخطرة',
    category: 'بيئية',
    criteria: 'تجميع بقايا الأحبار ومواد التنظيف الكيميائية في حاويات مغلقة وموسومة، وتسليمها لمتعامل معتمد وفق المرسوم 09-19.',
    legalReference: 'القانون 01-19 + المرسوم 05-315 + المرسوم 09-19.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRT-35-05',
    axis: 'السلامة من الحريق',
    category: 'سلامة',
    criteria: 'توفر مطفآت حريق مناسبة ومخارج طوارئ واضحة.',
    legalReference: 'القانون 19-02.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
];
