import { InspectionItem } from '../types';
import { baseFoodCriteria } from './baseFoodCriteria';

// Covers: "وحدة تخزين الزيتون والخضر" — olive and vegetable storage unit
const produceStorageSpecificCriteria: InspectionItem[] = [
  {
    id: 'PRD-01-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط تخزين وتسويق الزيتون والخضروات بالجملة، مع تحديد طاقة التخزين والأنواع المخزنة في الملف التقني.',
    legalReference: 'المرسوم التنفيذي 06-198 المادة 5 (رخصة الاستغلال) والمادة 13 (الملف التقني: الطاقة، التجهيزات، الموقع).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-02-01',
    axis: 'شروط التخزين',
    category: 'صحيه',
    criteria: 'تخزين الزيتون والخضروات في ظروف درجة الحرارة والرطوبة الملائمة لكل صنف (0-5°م للخضر، 7-15°م للزيتون) مع تهوية مناسبة.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 5 (مراقبة درجات الحرارة كنقطة تحكم حرجة لحفظ المنتجات الغذائية) + القرارات الوزارية الخاصة بشروط حفظ المنتجات الفلاحية الطازجة.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-02-02',
    axis: 'شروط التخزين',
    category: 'صحيه',
    criteria: 'رفع المنتجات عن الأرض على رفوف أو بليطات (palettes) لضمان التهوية ومنع تلوثها بالرطوبة الأرضية.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 13 (تنظيم التخزين: عدم وضع المنتجات الغذائية مباشرة على الأرض).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-02-03',
    axis: 'شروط التخزين',
    category: 'صحيه',
    criteria: 'الفصل بين المنتجات المختلفة وعدم تخزين مواد ذات روائح قوية (بصل، ثوم) بجوار منتجات حساسة للامتصاص (بطاطس، تفاح).',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 13 (الفصل بين مناطق تخزين المنتجات المختلفة لمنع التلوث المتبادل).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-03-01',
    axis: 'نظافة فضاءات التخزين',
    category: 'نظافة',
    criteria: 'نظافة عامة لفضاءات التخزين: أرضيات وجدران خالية من التلف والتشققات، سهلة التنظيف، وخالية من تراكم البقايا النباتية المتعفنة.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 15 و 16 (الأرضيات والجدران: غير منفذة، قابلة للغسل، في حالة جيدة في منشآت التخزين الغذائي).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-03-02',
    axis: 'نظافة فضاءات التخزين',
    category: 'نظافة',
    criteria: 'برنامج دوري لتنظيف وتطهير فضاءات التخزين، الرفوف، وآليات التبريد بعد كل دفعة أو بصفة منتظمة، موثق في سجل.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 19 (برامج التنظيف والتطهير الموثقة في المنشآت الغذائية).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-04-01',
    axis: 'مكافحة الآفات',
    category: 'بيئية',
    criteria: 'وجود برنامج فعّال لمكافحة القوارض والحشرات (خاصة الذباب، عث التخزين، الفطريات) مع خريطة فخاخ محدّثة وسجل للتدخلات.',
    legalReference: 'القانون 03-10 المادة 68 + المرسوم التنفيذي 17-140 المادة 26 (إلزامية وجود إجراءات فعالة لمكافحة الحيوانات الضارة في منشآت التخزين الغذائي).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-04-02',
    axis: 'مكافحة الآفات',
    category: 'بيئية',
    criteria: 'سد جميع الثغرات والفتحات التي تسمح بدخول القوارض، وتركيب شبك معدني على فتحات التهوية لمنع دخول الحشرات والطيور.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 26 (وسائل الوقاية من الحيوانات الضارة: الشبكات الواقية، سد الفتحات، الحواجز الطبيعية).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-05-01',
    axis: 'المياه والتخلص من النفايات',
    category: 'بيئية',
    criteria: 'إزالة المنتجات التالفة أو المتعفنة بانتظام من فضاءات التخزين ووضعها في حاويات نفايات مغطاة بعيداً عن المنتجات الصالحة للاستهلاك.',
    legalReference: 'المرسوم التنفيذي 17-140 المادتان 32 و 33 (إزالة النفايات والمنتجات التالفة بسرعة من مناطق الحفظ الغذائي).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-05-02',
    axis: 'التتبعية',
    category: 'تنظيمية',
    criteria: 'وجود سجل استقبال وتوزيع يتيح تتبع مصدر كل دفعة من المنتجات (المورد، تاريخ الاستقبال، الكمية) والجهة الموزعة إليها.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 4 (التتبعية Traçabilité في منشآت تخزين المواد الغذائية كجزء من متطلبات HACCP).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];

export const produceStorageCriteria: InspectionItem[] = [
  ...produceStorageSpecificCriteria,
  ...baseFoodCriteria,
];
