import { InspectionItem } from '../types';

// Covers: "وحدة تخزين الزيتون والخضر" — olive and vegetable storage unit
export const produceStorageCriteria: InspectionItem[] = [
  {
    id: 'PRD-01-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر رخصة استغلال سارية لنشاط تخزين وتسويق الزيتون والخضروات بالجملة، مع تحديد طاقة التخزين والأنواع المخزنة في الملف التقني.',
    legalReference: 'المرسوم التنفيذي 06-198 كما عُدِّل بالمرسومَيْن 22-167 و24-196، المادة 5 (رخصة الاستغلال) والمادة 13 (الملف التقني: الطاقة، التجهيزات، الموقع).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-02-01',
    axis: 'شروط التخزين',
    category: 'صحيه',
    criteria: 'تخزين الزيتون والخضروات في ظروف درجة الحرارة والرطوبة الملائمة لكل صنف (0-5°م للخضر، 7-15°م للزيتون) مع تهوية مناسبة.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 5 (مراقبة درجات الحرارة كنقطة تحكم حرجة لحفظ المنتجات الغذائية) + القرارات الوزارية الخاصة بشروط حفظ المنتجات الفلاحية الطازجة.',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-02-02',
    axis: 'شروط التخزين',
    category: 'صحيه',
    criteria: 'رفع المنتجات عن الأرض على رفوف أو بليطات (palettes) لضمان التهوية ومنع تلوثها بالرطوبة الأرضية.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 13 (تنظيم التخزين: عدم وضع المنتجات الغذائية مباشرة على الأرض).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-02-03',
    axis: 'شروط التخزين',
    category: 'صحيه',
    criteria: 'الفصل بين المنتجات المختلفة وعدم تخزين مواد ذات روائح قوية (بصل، ثوم) بجوار منتجات حساسة للامتصاص (بطاطس، تفاح).',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 13 (الفصل بين مناطق تخزين المنتجات المختلفة لمنع التلوث المتبادل).',
    severity: 'medium',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-03-01',
    axis: 'نظافة فضاءات التخزين',
    category: 'نظافة',
    criteria: 'نظافة عامة لفضاءات التخزين: أرضيات وجدران خالية من التلف والتشققات، سهلة التنظيف، وخالية من تراكم البقايا النباتية المتعفنة.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 15 و 16 (الأرضيات والجدران: غير منفذة، قابلة للغسل، في حالة جيدة في منشآت التخزين الغذائي).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'PRD-03-02',
    axis: 'نظافة فضاءات التخزين',
    category: 'نظافة',
    criteria: 'برنامج دوري لتنظيف وتطهير فضاءات التخزين، الرفوف، وآليات التبريد بعد كل دفعة أو بصفة منتظمة، موثق في سجل.',
    legalReference: 'المرسوم التنفيذي 17-140 المادة 19 (برامج التنظيف والتطهير الموثقة في المنشآت الغذائية).',
    severity: 'medium',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  // PRD-04-01 and PRD-04-02 removed — pest control covered by BGN-07-01/02/04 (S9 pest dedup)
  {
    id: 'PRD-05-01',
    axis: 'المياه والتخلص من النفايات',
    category: 'بيئية',
    criteria: 'إزالة المنتجات التالفة أو المتعفنة بانتظام من فضاءات التخزين ووضعها في حاويات نفايات مغطاة بعيداً عن المنتجات الصالحة للاستهلاك.',
    legalReference: 'المرسوم التنفيذي 17-140 المادتان 32 و 33.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // PRD-05-02 removed — traceability now covered by BFD-08-01 in baseFoodCriteria (Phase 3 dedup)
];
