// src/criteria/slaughterhouseSmallCriteria.ts
// W42 (2026-08-10): SLH-08-01 legalReference corrected — Loi 03-10 "المواد 15–22" → "المواد 14–21".
//   Same W41 fix applied to abattoirCriteria.ts now applied here.
//   Art.14 is the root EIE obligation article (missed by the old range).
//   Art.22 = fiscal instruments — completely unrelated to EIE. Confirmed by direct read.
//   Décret 04-82 Arts.6 (SLH-05-02) + Arts.9 (SLH-05-03) confirmed correct by direct read.
//   ABT-AX6-02 [À VÉRIFIER] on Annex II g/tonne — intentional per W10 decision. No change.
import { InspectionItem } from '../types';

export const slaughterhouseSmallCriteria: InspectionItem[] = [
  {
    id: 'SLH-05-01',
    axis: 'هوية المنشأة والوثائق',
    category: 'تنظيمية',
    criteria: 'توفر تصريح استغلال أو رخصة سارية لنشاط مذبحة دواجن بسعة أقل من 500 كغ/يوم، مع توافق الطاقة اليومية ونوع الذبائح مع ما هو مصرح به.',
    legalReference: 'المادتان 5 و8 من المرسوم التنفيذي 06-198 المعدَّل بالمرسومين 22-167 و24-196 المتعلق بالتنظيم المطبق على المؤسسات المصنفة (نظام الترخيص والتصريح حسب درجة الخطر وحجم النشاط).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-05-02',
    axis: 'الذبح والفحص الصحي',
    category: 'صحية',
    criteria: 'تنظيم فحص صحي قبل الذبح للدواجن (ante mortem) للتأكد من خلوّها من الأمراض الظاهرة واستبعاد الحالات المشتبه فيها قبل الدخول إلى غرفة الذبح.',
    // W42 (2026-08-10): CONFIRMED CLEAN — Art.6 of Décret 04-82 is the correct article
    // (ante mortem health inspection requirement). No change needed.
    legalReference: 'المادة 6 من المرسوم التنفيذي 04-82 المؤرخ في 24 مارس 2004 المتعلق بالاعتماد الصحي للمنشآت المرتبطة بالحيوانات والمنتوجات الحيوانية، التي تشترط إجراء المراقبة الصحية قبل ذبح الدواجن.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-05-03',
    axis: 'الذبح والفحص الصحي',
    category: 'صحية',
    criteria: 'إجراء فحص بعدي للذبائح (post mortem) للتأكد من سلامة الذبائح واستبعاد الأجزاء أو الذبائح غير الصالحة للاستهلاك وتوجيهها لمسار نفايات خاص.',
    // W42 (2026-08-10): CONFIRMED CLEAN — Art.9 of Décret 04-82 is the correct article
    // (post mortem inspection requirement). No change needed.
    legalReference: 'المادة 9 من المرسوم 04-82 بخصوص الاعتماد الصحي للمنشآت الحيوانية، والمادة 3 من المرسوم 17-140 المؤرخ في 27 مارس 2017 حول سلامة المنتجات الغذائية ذات الأصل الحيواني.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-05-04',
    axis: 'مخلفات الذبح',
    category: 'بيئية',
    criteria: 'فصل الدم والأحشاء والمحتويات الصلبة عن مياه الغسل قبل وصولها إلى الحفرة المتعفنة أو شبكة الصرف، مع تجميعها في أوعية أو حاويات مخصصة. عند التصريف في الشبكة العمومية أو الوسط الطبيعي: قياس المعاملات عند نقطة التصريف والتحقق من عدم تجاوز: DBO5 ≤35 ملغ/ل، DCO ≤120 ملغ/ل، MES ≤35 ملغ/ل، pH بين 6.5 و8.5.',
    legalReference: 'المادة 34 من القانون 01-19 المؤرخ في 12 ديسمبر 2001 المتعلق بتسيير النفايات ومراقبتها وإزالتها، والمادة 12 من القانون 03-10 المؤرخ في 19 يوليو 2003 المتعلق بحماية البيئة (منع صرف مخلفات الذبح مباشرة دون معالجة). المرسوم التنفيذي 06-141 الملحق الأول (القيم القصوى للمصبات الصناعية السائلة: DBO5 ≤35، DCO ≤120، MES ≤35، pH 6.5–8.5).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'DBO5 عند نقطة التصريف',
      max: 35,
      warningMax: 28,
      step: 1,
      upperLimit: true,
    },
  },
  {
    id: 'SLH-05-04B',
    axis: 'مخلفات الذبح',
    category: 'بيئية',
    criteria: 'قياس الطلب الكيميائي للأكسجين (DCO) عند نقطة التصريف النهائي والتحقق من عدم تجاوز 120 ملغ/ل.',
    legalReference: 'المرسوم التنفيذي 06-141 الملحق الأول (القيمة القصوى لـ DCO: 120 ملغ/ل).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'DCO عند نقطة التصريف',
      max: 120,
      warningMax: 100,
      step: 1,
      upperLimit: true,
    },
  },
  {
    id: 'SLH-05-04C',
    axis: 'مخلفات الذبح',
    category: 'بيئية',
    criteria: 'قياس المواد العالقة الكلية (MES) عند نقطة التصريف النهائي والتحقق من عدم تجاوز 35 ملغ/ل.',
    legalReference: 'المرسوم التنفيذي 06-141 الملحق الأول (القيمة القصوى لـ MES: 35 ملغ/ل).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'mg/L',
      labelAr: 'MES عند نقطة التصريف',
      max: 35,
      warningMax: 28,
      step: 1,
      upperLimit: true,
    },
  },
  {
    id: 'SLH-05-04D',
    axis: 'مخلفات الذبح',
    category: 'بيئية',
    criteria: 'قياس درجة الحموضة (pH) لمياه الصرف عند نقطة التصريف النهائي والتحقق من بقائها في النطاق المسموح به (6.5–8.5).',
    legalReference: 'المرسوم التنفيذي 06-141 الملحق الأول (نطاق pH المسموح: 6.5–8.5).',
    severity: 'high',
    controlType: 'measurement',
    complianceStatus: 'not-evaluated',
    numericField: {
      unit: 'pH',
      labelAr: 'درجة الحموضة عند نقطة التصريف',
      min: 6.5,
      max: 8.5,
      warningMin: 6.8,
      warningMax: 8.2,
      step: 0.1,
      upperLimit: false,
    },
  },
  {
    id: 'SLH-05-05',
    axis: 'مخلفات الذبح',
    category: 'بيئية',
    criteria: 'تخزين مخلفات الذبح الصلبة غير الصالحة للاستهلاك (أحشاء مرفوضة، أجزاء مصادرة) في حاويات مغلقة، والتعاقد مع متعامل معتمد لجمعها ونقلها ومعالجتها.',
    legalReference: 'المادة 17 من القانون 01-19 المتعلق بتسيير النفايات، المادة 3 من المرسوم 06-104 المؤرخ في 28 فبراير 2006 (قائمة النفايات الخاصة الخطرة)، والمادة 2 من المرسوم 05-315 المحدد لكيفيات التصريح بالنفايات الخاصة.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-05-06',
    axis: 'مياه الغسل والتطهير',
    category: 'صحية',
    criteria: 'استعمال ماء صالح للشرب في غسل الدواجن والأدوات والأسطح، مع احترام الحد الأدنى للكلور الحر المتبقي عند استعمال ماء الشبكة.',
    legalReference: 'المادة 25 من المرسوم 17-140 المؤرخ في 27 مارس 2017 بخصوص الماء الصالح للشرب في المنشآت الغذائية، والمادة 4 من المرسوم 11-125 المعدل بالمرسوم 14-96 الذي يحدد الحد الأدنى للكلور الحر المتبقي بـ 0.1 ملغ/ل.',
    severity: 'high',
    controlType: 'test',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-05-07',
    axis: 'غرف التبريد',
    category: 'صحية',
    criteria: 'توفر ثلاجات أو غرف تبريد ملائمة لحفظ لحوم الدواجن بدرجة حرارة مناسبة (عادة بين 0 و5°م) حسب نوع المنتجات، مع ميزان حرارة داخلي.',
    legalReference: 'المادة 20 من المرسوم 17-140 التي تنص على وجوب توفير تجهيزات تبريد كافية مزودة بأجهزة قياس الحرارة في المنشآت الغذائية التي تتعامل مع منتجات حيوانية.',
    severity: 'high',
    controlType: 'test',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-05-08',
    axis: 'نظافة قاعة الذبح',
    category: 'نظافة',
    criteria: 'أرضيات قاعة الذبح مائلة نحو قنوات صرف مزودة بسيفونات، مع عدم وجود برك دائمة من الدم أو المياه، وبرنامج تنظيف وتطهير بعد دورات الذبح.',
    legalReference: 'المادتان 15 و27 من المرسوم 17-140 (منحدرات الأرضيات وقنوات الصرف في المنشآت الغذائية)، والمادة 12 من القانون 03-10 بخصوص منع تلوث المياه والأوساط الداخلية.',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-05-09',
    axis: 'صحة وسلوك العمال',
    category: 'صحية',
    criteria: 'ارتداء عمال المذبحة لملابس عمل نظيفة ومناسبة (مآزر، أغطية رأس، أحذية خاصة) مع منع الأكل والشرب والتدخين في منطقة الذبح.',
    legalReference: 'المادتان 35 و36 من المرسوم التنفيذي 17-140 المتعلق بشروط النظافة والنظافة الصحية للمؤسسات الغذائية (ملابس العمل، سلوك المستخدمين، المنع الصريح للتدخين).',
    severity: 'high',
    controlType: 'visual',
    complianceStatus: 'not-evaluated',
  },
  // SLH-05-10 removed — pest control covered by BGN-07-01/02/04 (S9 pest dedup)
  {
    id: 'SLH-06-01',
    axis: 'نظام HACCP وسلامة الغذاء',
    category: 'صحية',
    criteria: 'تطبيق مبادئ HACCP أو نظام مكافئ: تحديد نقاط التحكم الحرجة (CCP) في خط الذبح (دم، سلخ، تحرير الأحشاء)، مع سجلات مراقبة موثقة لكل CCP.',
    legalReference: 'المادة 5 من المرسوم التنفيذي 17-140 المؤرخ في 27 مارس 2017 التي تُلزم مشغلي المنشآت الغذائية بتطبيق نظام تحليل الأخطار ونقاط التحكم الحرجة (HACCP) أو إجراءات مكافئة مستندة إلى مبادئه.',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-07-01',
    axis: 'النفايات البيطرية والطبية',
    category: 'بيئية',
    criteria: 'الفصل الميداني للنفايات البيطرية الخطرة الناتجة عن فحص الدواجن وعمليات الذبح وفق نظام التدفقات الثلاث: الأخضر (نفايات عادية)، الأصفر (نفايات خاصة غير خطرة)، الأحمر (نفايات معدية/حادة). وجود حاويات مُصنَّفة لكل تدفق، مع عقد مع متعامل معتمد لجمع النفايات الخطرة ومعالجتها، والاحتفاظ ببيانات النقل.',
    legalReference: 'المرسوم التنفيذي 03-478 (9 ديسمبر 2003) المتعلق بتسيير النفايات الطبية والبيطرية الخاصة الخطرة (نظام التدفقات الثلاث، إلزامية الفصل والتوثيق).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
  {
    id: 'SLH-08-01',
    axis: 'دراسة التأثير البيئي',
    category: 'بيئية',
    criteria: 'توفر دراسة تأثير على البيئة (EIE) أو موجز بيئي معتمد من الوالي المختص للمنشآت المصنفة من الفئة الأولى والثانية، وعدم تجاوز حدود التلوث المحددة فيها (DBO5، روائح، ضجيج، مخلفات ذبح)، مع التجديد الدوري لهذه الدراسة عند إجراء توسعات أو تغييرات جوهرية في الطاقة التذبيحية.',
    // W42 (2026-08-10): CORRECTED — "المواد 15–22" → "المواد 14–21".
    // Same correction as W41 on abattoirCriteria.ts (BGN-10-01 + GPL-05-01).
    // Art.14 = root EIE obligation (missed by old range). Art.22 = fiscal instruments (unrelated).
    // Confirmed by direct read: Arts.14–21 form the complete EIE chapter (Chapitre II, Titre II).
    legalReference: 'القانون 03-10 المواد 14–21 (إلزامية دراسة التأثير على البيئة للمنشآت المصنفة — المادة 14 هي الأساس الجذري لإلزامية دراسة EIE). المرسوم التنفيذي 07-145 (كيفيات تطبيق دراسة التأثير على البيئة). المرسوم التنفيذي 06-198 كما عُدِّل بالمرسومَيْن 22-167 و24-196 (إدراج مذابح الدواجن في قائمة المنشآت المصنفة ذات التأثير البيئي).',
    severity: 'high',
    controlType: 'doc',
    complianceStatus: 'not-evaluated',
  },
];
