import json
from pathlib import Path
ROOT=Path('/home/ubuntu/legal_compare_repo'); W=ROOT/'work'/'comparison'; OUT=ROOT/'repo'/'legal_refs'
baseline={r['markdown']:r for r in json.loads((W/'baseline_block_results.json').read_text())}
after={r['markdown']:r for r in json.loads((W/'body_results.json').read_text())}
lines=['# Legal Markdown Gap-Fill Report','', '**Date:** 2026-08-17','', 'This report records the gap-filling pass applied on the review branch. The PDFs remain the authoritative sources; the Markdown files are derived AI retrieval references.','', '## Applied corrections','', 'The most material confirmed gap was in `decret-21-261-esp-equipements-hydrocarbures.md`. Its Articles 50–55 did not match the attached `dec21-261.pdf` wording, and Article 56 duplicated the Article 57 dossier text. The file was corrected against PDF pages 11–12: the source Articles 50–55 were restored, the actual Article 56 was inserted, Article 57 was retained, and the apparent `taraqe` typo was corrected to `tarage`. Source-page comments were added at the corrected passage.','', 'The broader corpus was upgraded with provenance front matter, source hashes, quality statuses, AI safety notices, and article/page markers where automated mapping was recoverable. Six supplied PDFs without direct repository counterparts were added as `source-only-*.md` files marked discovery-only and review-required.','', '## Before-after coverage for mapped pairs','', '| Markdown | Before coverage | After body coverage | Change | Status |','|---|---:|---:|---:|---|']
for md in sorted(after):
    b=baseline.get(md,{}).get('md_coverage'); a=after[md].get('md_coverage'); status='improved' if b is not None and a>b+0.001 else ('unchanged' if b is not None and abs(a-b)<=0.001 else 'reassessed')
    lines.append(f"| `{md}` | {b if b is not None else '—'} | {a} | {round(a-b,4) if b is not None else '—'} | {status} |")
lines += ['', '## Validation result', '', 'The generated corpus validation checked 48 Markdown/reference files for required safety markers, source hashes, and status consistency. It reported zero issues. The detailed machine-readable validation result is stored in `VALIDATION_RESULT.json`.', '', '## Remaining review-required items', '', 'OCR-derived files, partial or low-coverage pairs, source-only extractions, tables, annexes, and full-Journal PDFs still require page-level human review before any exact legal quotation or definitive compliance conclusion.']
(OUT/'GAP_FILL_REPORT.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(OUT/'GAP_FILL_REPORT.md')
