// src/facilitiesData.ts
// بيانات محدثة للمنشآت المصنفة في بلدية سيدي إبراهيم
// تم التحديث في 2026-03-15

import { Facility } from './types';

export const facilities: Facility[] = [
  // ========== أولاً: المنشآت المرخصة ==========
  {
    id: 'lic-001',
    projectName: 'مخبزة صناعية - يحياوي نورالدين',
    ownerName: 'يحياوي نورالدين',
    activity: 'مخبزة صناعية',
    address: 'شارع عزة عبد القادر',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.566363, 35.257844',
  },
  {
    id: 'lic-002',
    projectName: 'مخبزة صناعية - بلفكرون معاشو',
    ownerName: 'بلفكرون معاشو',
    activity: 'مخبزة صناعية',
    address: 'شارع الأمير عبد القادر',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: '',
  },
  {
    id: 'lic-003',
    projectName: 'مخبزة صناعية - الميهوبي النواري',
    ownerName: 'الميهوبي النواري',
    activity: 'مخبزة صناعية',
    address: 'شارع عزة عبد القادر',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.564401, 35.255855',
  },
  {
    id: 'lic-004',
    projectName: 'مذبحة دواجن ≤500 كغ/ي - سالم بوزيان (قدور)',
    ownerName: 'سالم بوزيان (قدور)',
    activity: 'مذبحة دواجن ≤500 كغ/ي',
    address: 'مستثمرة سالم هاشمي',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.558027, 35.259536',
  },
  {
    id: 'lic-005',
    projectName: 'مذبحة دواجن ≤500 كغ/ي - سالم سفيان',
    ownerName: 'سالم سفيان',
    activity: 'مذبحة دواجن ≤500 كغ/ي',
    address: 'مستثمرة سالم هاشمي',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.558027, 35.259536',
  },
  {
    id: 'lic-006',
    projectName: 'مذبحة دواجن ≤500 كغ/ي - سمير عبد القادر',
    ownerName: 'سمير عبد القادر',
    activity: 'مذبحة دواجن ≤500 كغ/ي',
    address: 'مزرعة العقيد لطفي',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.577993, 35.259601',
  },
  {
    id: 'lic-007',
    projectName: 'مذبحة دواجن ≤500 كغ/ي - نيازي عبد الله',
    ownerName: 'نيازي عبد الله',
    activity: 'مذبحة دواجن ≤500 كغ/ي',
    address: 'مستثمرة بودالي بعكية',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.558027, 35.259536',
  },
  {
    id: 'lic-008',
    projectName: 'غرفة تبريد - غلامون محمد أمين',
    ownerName: 'غلامون محمد أمين',
    activity: 'غرفة تبريد',
    address: 'حي 125 مسكن الحرية',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.568395, 35.259111',
  },
  {
    id: 'lic-009',
    projectName: 'تعبئة مواد شبه صيدلانية - متاجر خديجة',
    ownerName: 'متاجر خديجة',
    activity: 'تعبئة مواد شبه صيدلانية',
    address: 'شارع عزة عبد القادر',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.564320, 35.254940',
  },
  {
    id: 'lic-010',
    projectName: 'غسل وتشحيم السيارات - عبد الرحمان بودراية',
    ownerName: 'عبد الرحمان بودراية',
    activity: 'غسل وتشحيم السيارات',
    address: 'شارع عزة عبد القادر',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.567027, 35.259822',
  },
  {
    id: 'lic-011',
    projectName: 'غسل وتشحيم السيارات - تيفريت بلال',
    ownerName: 'تيفريت بلال',
    activity: 'غسل وتشحيم السيارات',
    address: 'شارع عزة عبد القادر',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.566752, 35.259584',
  },
  {
    id: 'lic-012',
    projectName: 'تركيب GPL/C - لخصر شاوش عبد القادر',
    ownerName: 'لخصر شاوش عبد القادر',
    activity: 'تركيب GPL/C',
    address: 'شارع جابر ابن حيان',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.564505, 35.259820',
  },
  {
    id: 'lic-013',
    projectName: 'منشأة صناعة تغذية حيوانية - بنابي يحي',
    ownerName: 'بنابي يحي',
    activity: 'منشأة صناعة تغذية حيوانية',
    address: 'شارع سي عبد الكريم',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.568919, 35.261207',
  },
  {
    id: 'lic-014',
    projectName: 'وحدة تخزين الزيتون والخضر - طالبي عبد الرحمن',
    ownerName: 'طالبي عبد الرحمن',
    activity: 'وحدة تخزين الزيتون والخضر',
    address: 'القسمة 05 مجموعة 51 منطقة عزة عبد القادر',
    licenseType: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    licenseDetails: 'تصريح رئيس المجلس الشعبي البلدي الفئة الرابعة',
    year: '',
    category: 'الفئة الرابعة',
    notes: 'الإحداثيات: -0.574024, 35.270588',
  },

  // ========== ثانياً: المنشآت الناشطة بدون رخصة ==========
  {
    id: 'unlic-001',
    projectName: 'إنتاج أغذية الأنعام (مؤسسة عمومية اقتصادية)',
    ownerName: '--',
    activity: 'إنتاج أغذية الأنعام (مؤسسة عمومية اقتصادية)',
    address: 'شارع محمد بزروقي',
    licenseType: 'في إطار التسوية',
    licenseDetails: 'في إطار التسوية',
    year: '',
    category: '',
    notes: 'الإحداثيات: -0.567433, 35.257202',
  },
  {
    id: 'unlic-002',
    projectName: 'مفرخة الدواجن (مؤسسة عمومية اقتصادية)',
    ownerName: '--',
    activity: 'مفرخة الدواجن (مؤسسة عمومية اقتصادية)',
    address: 'شارع محمد بزروقي',
    licenseType: 'في إطار التسوية',
    licenseDetails: 'في إطار التسوية',
    year: '',
    category: '',
    notes: 'الإحداثيات: -0.568985, 35.258323',
  },
  {
    id: 'unlic-003',
    projectName: 'تربية الدواجن (مؤسسة عمومية اقتصادية)',
    ownerName: '--',
    activity: 'تربية الدواجن (مؤسسة عمومية اقتصادية)',
    address: 'شارع عزالدين يوسف، حي كاستور',
    licenseType: 'في إطار التسوية',
    licenseDetails: 'في إطار التسوية',
    year: '',
    category: '',
    notes: 'الإحداثيات: -0.570735, 35.255972',
  },
  {
    id: 'unlic-004',
    projectName: 'ذبح وبيع الدواجن (مؤسسة عمومية اقتصادية)',
    ownerName: '--',
    activity: 'ذبح وبيع الدواجن (مؤسسة عمومية اقتصادية)',
    address: 'شارع محمد بزروقي',
    licenseType: 'في إطار التسوية',
    licenseDetails: 'في إطار التسوية',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-005',
    projectName: 'ذبح وبيع الدواجن (مؤسسة عمومية اقتصادية)',
    ownerName: 'Remchavi',
    activity: 'ذبح وبيع الدواجن (مؤسسة عمومية اقتصادية)',
    address: 'غير محدد',
    licenseType: 'في إطار التسوية',
    licenseDetails: 'في إطار التسوية',
    year: '',
    category: '',
    notes: 'الإحداثيات: -0.570306, 35.260289',
  },
  {
    id: 'unlic-006',
    projectName: 'مطبعة خاصة بإنتاج لوازم مدرسية ومستلزمات المكاتب',
    ownerName: 'قدوري قويدر',
    activity: 'مطبعة خاصة بإنتاج لوازم مدرسية ومستلزمات المكاتب',
    address: 'شارع عزة عبد القادر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-007',
    projectName: 'منشأة صناعة تغذية حيوانية',
    ownerName: 'دوار عمر',
    activity: 'منشأة صناعة تغذية حيوانية',
    address: 'شارع الاستقلال',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-008',
    projectName: 'ميكانيك السيارات',
    ownerName: 'بوعرعارة عبد القادر',
    activity: 'ميكانيك السيارات',
    address: 'شارع الأمير عبد القادر، حي 20 مسكن ريفي',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-009',
    projectName: 'ميكانيك',
    ownerName: 'دوينة حمزة',
    activity: 'ميكانيك',
    address: 'حي مرينة',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-010',
    projectName: 'ميكانيك',
    ownerName: 'بلبوش سيف الدين',
    activity: 'ميكانيك',
    address: 'شارع العقيد لطفي',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-011',
    projectName: 'ميكانيك',
    ownerName: 'بلبوش حمزة',
    activity: 'ميكانيك',
    address: 'شارع الاستقلال',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-012',
    projectName: 'ميكانيك',
    ownerName: 'بوسكين عباس',
    activity: 'ميكانيك',
    address: 'شارع الاستقلال',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-013',
    projectName: 'ميكانيك السيارات',
    ownerName: 'صحبي عباس',
    activity: 'ميكانيك السيارات',
    address: 'شارع عبار ناصر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-014',
    projectName: 'ميكانيك السيارات',
    ownerName: 'عوني غالم',
    activity: 'ميكانيك السيارات',
    address: 'شارع 24 فيفري',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-015',
    projectName: 'ميكانيك السيارات',
    ownerName: 'عزوز بغداد',
    activity: 'ميكانيك السيارات',
    address: 'شارع سي عبد الكريم',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-016',
    projectName: 'ميكانيك السيارات',
    ownerName: 'عوني قادة',
    activity: 'ميكانيك السيارات',
    address: 'شارع عبار ناصر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-017',
    projectName: 'ورشة طلاء السيارات',
    ownerName: 'عوني أحمد',
    activity: 'ورشة طلاء السيارات',
    address: 'شارع 24 فيفري',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-018',
    projectName: 'ورشة طلاء السيارات',
    ownerName: 'صديقي نور الدين',
    activity: 'ورشة طلاء السيارات',
    address: 'شارع العقيد لطفي',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-019',
    projectName: 'ورشة طلاء السيارات',
    ownerName: 'مباركي عباس',
    activity: 'ورشة طلاء السيارات',
    address: '08 ماي 1945',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-020',
    projectName: 'ورشة نجارة',
    ownerName: 'يحياوي محمد',
    activity: 'ورشة نجارة',
    address: 'شارع فرحات عباس',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-021',
    projectName: 'ورشة نجارة (كبير ميلود)',
    ownerName: 'كبير ميلود',
    activity: 'ورشة نجارة',
    address: 'شارع محمد خميستي',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-022',
    projectName: 'صناعة الرخام',
    ownerName: 'ذباب نصر الدين',
    activity: 'صناعة الرخام',
    address: 'شارع عقبة ابن نافع',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-023',
    projectName: 'صناعة الرخام',
    ownerName: 'خفوس إسماعيل',
    activity: 'صناعة الرخام',
    address: 'شارع الأمير عبد القادر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-024',
    projectName: 'غسل وتشحيم السيارات',
    ownerName: 'بلبوش سيف الدين',
    activity: 'غسل وتشحيم السيارات',
    address: 'شارع العقيد لطفي',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-025',
    projectName: 'مطبعة خاصة بإنتاج لوازم مدرسية ومستلزمات المكاتب',
    ownerName: 'قدوري قويدر',
    activity: 'مطبعة خاصة بإنتاج لوازم مدرسية ومستلزمات المكاتب',
    address: 'شارع عزة عبد القادر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-026',
    projectName: 'ورشة حدادة (صناعة السياج)',
    ownerName: 'شمالي مراد',
    activity: 'ورشة حدادة (صناعة السياج)',
    address: 'شارع عبار ناصر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-027',
    projectName: 'ورشة حدادة',
    ownerName: 'لكرب عبد السلام',
    activity: 'ورشة حدادة',
    address: 'شارع القدس',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-028',
    projectName: 'ورشة حدادة',
    ownerName: 'ميلوة عبد السلام',
    activity: 'ورشة حدادة',
    address: 'شارع سي عبد الكريم',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-029',
    projectName: 'ورشة حدادة',
    ownerName: 'بوشيخي واسيني',
    activity: 'ورشة حدادة',
    address: 'شارع محمد خميستي',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-030',
    projectName: 'ورشة حدادة',
    ownerName: 'بن معاشو بومدين',
    activity: 'ورشة حدادة',
    address: 'شارع الشهداء',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-031',
    projectName: 'ورشة حدادة',
    ownerName: 'بلجة محمد أمين',
    activity: 'ورشة حدادة',
    address: 'حصة 24 محل، بوبرناس',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-032',
    projectName: 'ورشة نجارة الألمنيوم',
    ownerName: 'تقار بوحجلة',
    activity: 'ورشة نجارة الألمنيوم',
    address: 'حصة 24 محل، بوبرناس',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-033',
    projectName: 'ورشة نجارة الألمنيوم',
    ownerName: 'فقير عبد القادر',
    activity: 'ورشة نجارة الألمنيوم',
    address: 'حي 35 مسكن',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-034',
    projectName: 'تربية الدواجن (07 حظائر)',
    ownerName: 'مطرفي حبيب',
    activity: 'تربية الدواجن (07 حظائر)',
    address: 'دوار الملايكة',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: 'الإحداثيات: -0.595565, 35.253978',
  },
  {
    id: 'unlic-035',
    projectName: 'تربية الدواجن (03 حظائر)',
    ownerName: 'سالم قدور ولد بوزيان',
    activity: 'تربية الدواجن (03 حظائر)',
    address: 'المستثمرة الفلاحية سالم هاشمي',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: 'الإحداثيات: -0.558027, 35.259536',
  },
  {
    id: 'unlic-036',
    projectName: 'تربية الدواجن (حظيرتين)',
    ownerName: 'دوار قويدر',
    activity: 'تربية الدواجن (حظيرتين)',
    address: 'دوار السراخنة',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-037',
    projectName: 'تربية الدواجن (حظيرة)',
    ownerName: 'علام محمد',
    activity: 'تربية الدواجن (حظيرة)',
    address: 'منطقة عزة عبد القادر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-038',
    projectName: 'تربية الدواجن (حظيرتين)',
    ownerName: 'عدلي العربي',
    activity: 'تربية الدواجن (حظيرتين)',
    address: 'قسمة 05 مجموعة 49',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-039',
    projectName: 'تربية الدواجن (حظيرة)',
    ownerName: 'بيوسف عيسى',
    activity: 'تربية الدواجن (حظيرة)',
    address: 'منطقة عزة عبد القادر',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-040',
    projectName: 'تربية الدواجن (حظيرتين)',
    ownerName: 'بن دومة محمد',
    activity: 'تربية الدواجن (حظيرتين)',
    address: 'المستثمرة الفلاحية سلاك بن قدور',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-041',
    projectName: 'تربية الدواجن (حظيرة)',
    ownerName: 'بن سجاد محمد',
    activity: 'تربية الدواجن (حظيرة)',
    address: 'مزرعة بكير بن زلاط',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-042',
    projectName: 'تربية الدواجن (03 حظائر)',
    ownerName: 'بركاتي حميدة',
    activity: 'تربية الدواجن (03 حظائر)',
    address: 'وزار العيد',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },
  {
    id: 'unlic-043',
    projectName: 'تربية الدواجن (حظيرة)',
    ownerName: 'سالم قدور ولد غالم',
    activity: 'تربية الدواجن (حظيرة)',
    address: 'المستثمرة الفلاحية برنو',
    licenseType: 'بدون ترخيص',
    licenseDetails: 'بدون ترخيص',
    year: '',
    category: '',
    notes: '',
  },

  // ========== ثالثاً: المنشآت قيد الإنشاء ==========
  {
    id: 'const-001',
    projectName: 'ذبح الدواجن (أكثر من 500 كغ/ي وأقل من 2 طن/ي)',
    ownerName: 'عدلي العربي',
    activity: 'ذبح الدواجن (أكثر من 500 كغ/ي وأقل من 2 طن/ي)',
    address: 'قسمة 05 مجموعة 49',
    licenseType: 'رخصة رئيس المجلس الشعبي البلدي (منشأة مصنفة من الفئة الثالثة)',
    licenseDetails: 'رخصة رئيس المجلس الشعبي البلدي (منشأة مصنفة من الفئة الثالثة)',
    year: '',
    category: 'الفئة الثالثة',
    notes: 'قيد الإنشاء',
  },
];